-- 01 - Heq indekset e teperta (redundant)
--
-- Nje indeks eshte i teperte kur nje indeks tjeter ne te njejten tabele ka te njejtat kolona celes ne fillim
-- (ne te njejten rradhe) dhe permban te gjitha kolonat e tij te perfshira (INCLUDE): cdo kerkim qe perdor
-- indeksin e hequr mund te perdore ate qe mbetet. Indekset UNIQUE, PRIMARY KEY dhe me filter nuk preken.
-- Perfitimi: cdo INSERT/UPDATE/DELETE (importet, ruajtja e dokumenteve) mirembante keto indekse kot.
--
-- U kontrollua qe asnje procedure/view/funksion dhe asnje rresht kodi i AVEC nuk i permend me emer.
-- Rikthimi: 01-rollback-redundant-indexes.sql
-- I sigurt per t'u ekzekutuar disa here (IF EXISTS).
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
-- T_ARTIKULLI.idx_tartikulli_IDARTIKULLI (0 MB): i mbuluar nga PK_T_ARTIKULLI
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'idx_tartikulli_IDARTIKULLI')
    DROP INDEX [idx_tartikulli_IDARTIKULLI] ON dbo.[T_ARTIKULLI];

-- T_ARTIKULLI.IX_T_ARTIKULLI_IDARTIKULLI (0 MB): i mbuluar nga idx_tartikulli_IDARTIKULLI
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'IX_T_ARTIKULLI_IDARTIKULLI')
    DROP INDEX [IX_T_ARTIKULLI_IDARTIKULLI] ON dbo.[T_ARTIKULLI];

-- T_ARTIKULLI.IX_T_ARTIKULLI_IDNDERMARJE (0 MB): i mbuluar nga autokomplete
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'IX_T_ARTIKULLI_IDNDERMARJE')
    DROP INDEX [IX_T_ARTIKULLI_IDNDERMARJE] ON dbo.[T_ARTIKULLI];

-- T_ARTIKULLI.IX_T_ARTIKULLI_IDSTATUSDOK (0 MB): i mbuluar nga 20160208
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'IX_T_ARTIKULLI_IDSTATUSDOK')
    DROP INDEX [IX_T_ARTIKULLI_IDSTATUSDOK] ON dbo.[T_ARTIKULLI];

-- T_KLIENTFURNITOR.INDEX_T_KLIENTFURNITOR_LLOJIKF (0 MB): i mbuluar nga IX_KLIENTFURNITOR_Lloji_Aktiv_Nderm_Status
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KLIENTFURNITOR') AND name = N'INDEX_T_KLIENTFURNITOR_LLOJIKF')
    DROP INDEX [INDEX_T_KLIENTFURNITOR_LLOJIKF] ON dbo.[T_KLIENTFURNITOR];

-- T_KOKAMAGAZINA.idx_tkokamagazina_IDKOKAMAGAZINA (4 MB): i mbuluar nga IX_KOKAMAGAZINA_KONFIG
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'idx_tkokamagazina_IDKOKAMAGAZINA')
    DROP INDEX [idx_tkokamagazina_IDKOKAMAGAZINA] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKAMAGAZINA.idx_tkokamagazina_IDSTATUSDOK (6 MB): i mbuluar nga T_KOKAMAGAZINA_IDKONFIGAMBJENTE_04122018
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'idx_tkokamagazina_IDSTATUSDOK')
    DROP INDEX [idx_tkokamagazina_IDSTATUSDOK] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKAMAGAZINA.IX_KOKAMAGAZINA_KONFIG (7 MB): i mbuluar nga PK_T_KOKAMAGAZINA
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_KOKAMAGAZINA_KONFIG')
    DROP INDEX [IX_KOKAMAGAZINA_KONFIG] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKAMAGAZINA.IX_T_KOKAMAGAZINA_IDKOKAMAGAZINA (4 MB): i mbuluar nga IX_KOKAMAGAZINA_KONFIG
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDKOKAMAGAZINA')
    DROP INDEX [IX_T_KOKAMAGAZINA_IDKOKAMAGAZINA] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKAMAGAZINA.IX_T_KOKAMAGAZINA_IDKONFIGAMBJENTE (6 MB): i mbuluar nga IX_TK_KonfigNderm_Optimized
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDKONFIGAMBJENTE')
    DROP INDEX [IX_T_KOKAMAGAZINA_IDKONFIGAMBJENTE] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKAMAGAZINA.IX_T_KOKAMAGAZINA_IDSTATUSDOK (5 MB): i mbuluar nga T_KOKAMAGAZINA_IDKONFIGAMBJENTE_04122018
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDSTATUSDOK')
    DROP INDEX [IX_T_KOKAMAGAZINA_IDSTATUSDOK] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKAMAGAZINA.T_KOKAMAGAZINA_04122018_IDKONFIGAMBJENTE (9 MB): i mbuluar nga T_KOKAMAGAZINA_IDKONFIGAMBJENTE_04122018
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'T_KOKAMAGAZINA_04122018_IDKONFIGAMBJENTE')
    DROP INDEX [T_KOKAMAGAZINA_04122018_IDKONFIGAMBJENTE] ON dbo.[T_KOKAMAGAZINA];

-- T_KOKASHITJEHISTORIK.index_T_KOKASHITJEHISTORIK_nonclustered_05062018 (1 MB): i mbuluar nga index_T_KOKASHITJEHISTORIK_nonclustered_080620182
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKASHITJEHISTORIK') AND name = N'index_T_KOKASHITJEHISTORIK_nonclustered_05062018')
    DROP INDEX [index_T_KOKASHITJEHISTORIK_nonclustered_05062018] ON dbo.[T_KOKASHITJEHISTORIK];

-- T_kokashitjelogical.IX_kokashitjelogical_IdImport (1 MB): i mbuluar nga IX_kokashitjelogical_IdImport_KodNderm
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_kokashitjelogical') AND name = N'IX_kokashitjelogical_IdImport')
    DROP INDEX [IX_kokashitjelogical_IdImport] ON dbo.[T_kokashitjelogical];

-- T_KONFIGAMBJENTE.index_T_KONFIGAMBJENTE_20181203_03 (0 MB): i mbuluar nga index_T_NIVELREGJISTRIMI_20181203_02
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KONFIGAMBJENTE') AND name = N'index_T_KONFIGAMBJENTE_20181203_03')
    DROP INDEX [index_T_KONFIGAMBJENTE_20181203_03] ON dbo.[T_KONFIGAMBJENTE];

-- T_KONFIGAMBJENTE.IX_T_KONFIGAMBJENTE_IDKONFIGAMBJENTE (0 MB): i mbuluar nga PK_T_KONFIGAMBJENTE
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KONFIGAMBJENTE') AND name = N'IX_T_KONFIGAMBJENTE_IDKONFIGAMBJENTE')
    DROP INDEX [IX_T_KONFIGAMBJENTE_IDKONFIGAMBJENTE] ON dbo.[T_KONFIGAMBJENTE];

-- T_KONFIGAMBJENTE.IX_T_KONFIGAMBJENTE_IDNDERMARJE (0 MB): i mbuluar nga IND_T_KONFIGAMBJENTE_24_01_17_1
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KONFIGAMBJENTE') AND name = N'IX_T_KONFIGAMBJENTE_IDNDERMARJE')
    DROP INDEX [IX_T_KONFIGAMBJENTE_IDNDERMARJE] ON dbo.[T_KONFIGAMBJENTE];

-- T_KPF.T_KPF_KODIKPF (0 MB): i mbuluar nga index_T_KPF_24052018_02
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KPF') AND name = N'T_KPF_KODIKPF')
    DROP INDEX [T_KPF_KODIKPF] ON dbo.[T_KPF];

-- T_KUSHTEMPLATE.indexidkonvlera (5 MB): i mbuluar nga IX_KushTemplate_KonfigKusht
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KUSHTEMPLATE') AND name = N'indexidkonvlera')
    DROP INDEX [indexidkonvlera] ON dbo.[T_KUSHTEMPLATE];

-- T_LLOGARI.index_T_LLOGARI_24052018_01 (1 MB): i mbuluar nga T_LLOGARI_NRLLOGari_IDSTATUSDOK
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_LLOGARI') AND name = N'index_T_LLOGARI_24052018_01')
    DROP INDEX [index_T_LLOGARI_24052018_01] ON dbo.[T_LLOGARI];

-- T_NIVELREGJISTRIMI.index_T_NIVELREGJISTRIMI_nonclustered_08062018 (0 MB): i mbuluar nga index_T_NIVELREGJISTRIMI_20181203_01
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_NIVELREGJISTRIMI') AND name = N'index_T_NIVELREGJISTRIMI_nonclustered_08062018')
    DROP INDEX [index_T_NIVELREGJISTRIMI_nonclustered_08062018] ON dbo.[T_NIVELREGJISTRIMI];

-- T_NJESIADMINISTRATIVE.IX_T_NJESIADMINISTRATIVE_IDNJESIADM (0 MB): i mbuluar nga PK_T_NJESIADMINISTRATIVE
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_NJESIADMINISTRATIVE') AND name = N'IX_T_NJESIADMINISTRATIVE_IDNJESIADM')
    DROP INDEX [IX_T_NJESIADMINISTRATIVE_IDNJESIADM] ON dbo.[T_NJESIADMINISTRATIVE];

-- T_TRUPIMAGAZINA.index_T_TRUPIMAGAZINA_ktheSasineTotaleSipasArtikullit_Modifikim_10012019 (310 MB): i mbuluar nga IX_TM_ArtMagData_Optimized
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'index_T_TRUPIMAGAZINA_ktheSasineTotaleSipasArtikullit_Modifikim_10012019')
    DROP INDEX [index_T_TRUPIMAGAZINA_ktheSasineTotaleSipasArtikullit_Modifikim_10012019] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPIMAGAZINA.IX_T_TRUPIMAGAZINA_IDARTIKULL (102 MB): i mbuluar nga IX_TM_ArtMagData_Optimized
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_T_TRUPIMAGAZINA_IDARTIKULL')
    DROP INDEX [IX_T_TRUPIMAGAZINA_IDARTIKULL] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPIMAGAZINA.IX_T_TRUPIMAGAZINA_IDARTIKULL_DATA (131 MB): i mbuluar nga IX_T_TRUPIMAGAZINA_IDARTIKULL_DATA_IDKTHIMI
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_T_TRUPIMAGAZINA_IDARTIKULL_DATA')
    DROP INDEX [IX_T_TRUPIMAGAZINA_IDARTIKULL_DATA] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPIMAGAZINA.IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA (73 MB): i mbuluar nga IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA_IDARTIKULL_IDMAG_IDSTATUSDOK
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA')
    DROP INDEX [IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPIMAGAZINA.IX_TRUPIMAGAZINA_ART_MAG_DATA (329 MB): i mbuluar nga IX_TM_ArtMagData_Optimized
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_TRUPIMAGAZINA_ART_MAG_DATA')
    DROP INDEX [IX_TRUPIMAGAZINA_ART_MAG_DATA] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPIMAGAZINA.IX_TRUPIMAGAZINA_IDARTIKULL_IDMAG_DATA (307 MB): i mbuluar nga IX_TM_ArtMagData_Optimized
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_TRUPIMAGAZINA_IDARTIKULL_IDMAG_DATA')
    DROP INDEX [IX_TRUPIMAGAZINA_IDARTIKULL_IDMAG_DATA] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPIMAGAZINA.IX_TrupiMagazina_Koka_Art_Mag (151 MB): i mbuluar nga IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA_IDARTIKULL_IDMAG_IDSTATUSDOK
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_TrupiMagazina_Koka_Art_Mag')
    DROP INDEX [IX_TrupiMagazina_Koka_Art_Mag] ON dbo.[T_TRUPIMAGAZINA];

-- T_TRUPISHITJE.idx_ttrupishitje_IDSHITJEKOKA (46 MB): i mbuluar nga ind20160324_1
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPISHITJE') AND name = N'idx_ttrupishitje_IDSHITJEKOKA')
    DROP INDEX [idx_ttrupishitje_IDSHITJEKOKA] ON dbo.[T_TRUPISHITJE];
