-- Rikthen indekset qe heq 01-drop-redundant-indexes.sql (me te njejtat kolona).
SET NOCOUNT ON;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'idx_tartikulli_IDARTIKULLI')
    CREATE NONCLUSTERED INDEX [idx_tartikulli_IDARTIKULLI] ON dbo.[T_ARTIKULLI] ([IDARTIKULLI]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'IX_T_ARTIKULLI_IDARTIKULLI')
    CREATE NONCLUSTERED INDEX [IX_T_ARTIKULLI_IDARTIKULLI] ON dbo.[T_ARTIKULLI] ([IDARTIKULLI]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'IX_T_ARTIKULLI_IDNDERMARJE')
    CREATE NONCLUSTERED INDEX [IX_T_ARTIKULLI_IDNDERMARJE] ON dbo.[T_ARTIKULLI] ([IDNDERMARJE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_ARTIKULLI') AND name = N'IX_T_ARTIKULLI_IDSTATUSDOK')
    CREATE NONCLUSTERED INDEX [IX_T_ARTIKULLI_IDSTATUSDOK] ON dbo.[T_ARTIKULLI] ([IDSTATUSDOK]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KLIENTFURNITOR') AND name = N'INDEX_T_KLIENTFURNITOR_LLOJIKF')
    CREATE NONCLUSTERED INDEX [INDEX_T_KLIENTFURNITOR_LLOJIKF] ON dbo.[T_KLIENTFURNITOR] ([LLOJIKF]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'idx_tkokamagazina_IDKOKAMAGAZINA')
    CREATE NONCLUSTERED INDEX [idx_tkokamagazina_IDKOKAMAGAZINA] ON dbo.[T_KOKAMAGAZINA] ([IDKOKAMAGAZINA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'idx_tkokamagazina_IDSTATUSDOK')
    CREATE NONCLUSTERED INDEX [idx_tkokamagazina_IDSTATUSDOK] ON dbo.[T_KOKAMAGAZINA] ([IDSTATUSDOK]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_KOKAMAGAZINA_KONFIG')
    CREATE NONCLUSTERED INDEX [IX_KOKAMAGAZINA_KONFIG] ON dbo.[T_KOKAMAGAZINA] ([IDKOKAMAGAZINA]) INCLUDE ([IDKONFIGAMBJENTE], [IDLLOJDOKUMENTIMAGAZINE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDKOKAMAGAZINA')
    CREATE NONCLUSTERED INDEX [IX_T_KOKAMAGAZINA_IDKOKAMAGAZINA] ON dbo.[T_KOKAMAGAZINA] ([IDKOKAMAGAZINA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDKONFIGAMBJENTE')
    CREATE NONCLUSTERED INDEX [IX_T_KOKAMAGAZINA_IDKONFIGAMBJENTE] ON dbo.[T_KOKAMAGAZINA] ([IDKONFIGAMBJENTE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDSTATUSDOK')
    CREATE NONCLUSTERED INDEX [IX_T_KOKAMAGAZINA_IDSTATUSDOK] ON dbo.[T_KOKAMAGAZINA] ([IDSTATUSDOK]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'T_KOKAMAGAZINA_04122018_IDKONFIGAMBJENTE')
    CREATE NONCLUSTERED INDEX [T_KOKAMAGAZINA_04122018_IDKONFIGAMBJENTE] ON dbo.[T_KOKAMAGAZINA] ([IDSTATUSDOK], [IDNDERMVIT], [IDLLOJDOKUMENTIMAGAZINE]) INCLUDE ([IDKONFIGAMBJENTE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKASHITJEHISTORIK') AND name = N'index_T_KOKASHITJEHISTORIK_nonclustered_05062018')
    CREATE NONCLUSTERED INDEX [index_T_KOKASHITJEHISTORIK_nonclustered_05062018] ON dbo.[T_KOKASHITJEHISTORIK] ([IDKLIENTFURNITOR], [IDSHITJEKOKA], [IDSTATUSDOK]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_kokashitjelogical') AND name = N'IX_kokashitjelogical_IdImport')
    CREATE NONCLUSTERED INDEX [IX_kokashitjelogical_IdImport] ON dbo.[T_kokashitjelogical] ([IDIMPORTSHITJE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KONFIGAMBJENTE') AND name = N'index_T_KONFIGAMBJENTE_20181203_03')
    CREATE NONCLUSTERED INDEX [index_T_KONFIGAMBJENTE_20181203_03] ON dbo.[T_KONFIGAMBJENTE] ([IDKATDOK], [IDNDERMARJE]) INCLUDE ([IDKONFIGAMBJENTE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KONFIGAMBJENTE') AND name = N'IX_T_KONFIGAMBJENTE_IDKONFIGAMBJENTE')
    CREATE NONCLUSTERED INDEX [IX_T_KONFIGAMBJENTE_IDKONFIGAMBJENTE] ON dbo.[T_KONFIGAMBJENTE] ([IDKONFIGAMBJENTE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KONFIGAMBJENTE') AND name = N'IX_T_KONFIGAMBJENTE_IDNDERMARJE')
    CREATE NONCLUSTERED INDEX [IX_T_KONFIGAMBJENTE_IDNDERMARJE] ON dbo.[T_KONFIGAMBJENTE] ([IDNDERMARJE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KPF') AND name = N'T_KPF_KODIKPF')
    CREATE NONCLUSTERED INDEX [T_KPF_KODIKPF] ON dbo.[T_KPF] ([KODIKPF]) INCLUDE ([IDNDERMARJE], [IDSTATUSDOK]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KUSHTEMPLATE') AND name = N'indexidkonvlera')
    CREATE NONCLUSTERED INDEX [indexidkonvlera] ON dbo.[T_KUSHTEMPLATE] ([IDKUSHT]) INCLUDE ([IDKONFIGAMBJENTE], [VLERA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_LLOGARI') AND name = N'index_T_LLOGARI_24052018_01')
    CREATE NONCLUSTERED INDEX [index_T_LLOGARI_24052018_01] ON dbo.[T_LLOGARI] ([IDSTATUSDOK]) INCLUDE ([IDLLOGARI], [NRLLOGARI], [EMERLLOGARI_sq], [KPF1], [IDNDERMARJE]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_NIVELREGJISTRIMI') AND name = N'index_T_NIVELREGJISTRIMI_nonclustered_08062018')
    CREATE NONCLUSTERED INDEX [index_T_NIVELREGJISTRIMI_nonclustered_08062018] ON dbo.[T_NIVELREGJISTRIMI] ([KODI]) INCLUDE ([IDNIVEL]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_NJESIADMINISTRATIVE') AND name = N'IX_T_NJESIADMINISTRATIVE_IDNJESIADM')
    CREATE NONCLUSTERED INDEX [IX_T_NJESIADMINISTRATIVE_IDNJESIADM] ON dbo.[T_NJESIADMINISTRATIVE] ([IDNJESIADM]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'index_T_TRUPIMAGAZINA_ktheSasineTotaleSipasArtikullit_Modifikim_10012019')
    CREATE NONCLUSTERED INDEX [index_T_TRUPIMAGAZINA_ktheSasineTotaleSipasArtikullit_Modifikim_10012019] ON dbo.[T_TRUPIMAGAZINA] ([IDARTIKULL], [IDMAG], [DATA]) INCLUDE ([IDKOKAMAGAZINA], [SASIA], [KOEFICENTI], [SHENJA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_T_TRUPIMAGAZINA_IDARTIKULL')
    CREATE NONCLUSTERED INDEX [IX_T_TRUPIMAGAZINA_IDARTIKULL] ON dbo.[T_TRUPIMAGAZINA] ([IDARTIKULL]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_T_TRUPIMAGAZINA_IDARTIKULL_DATA')
    CREATE NONCLUSTERED INDEX [IX_T_TRUPIMAGAZINA_IDARTIKULL_DATA] ON dbo.[T_TRUPIMAGAZINA] ([IDARTIKULL], [DATA]) INCLUDE ([IDKTHIMI]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA')
    CREATE NONCLUSTERED INDEX [IX_T_TRUPIMAGAZINA_IDKOKAMAGAZINA] ON dbo.[T_TRUPIMAGAZINA] ([IDKOKAMAGAZINA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_TRUPIMAGAZINA_ART_MAG_DATA')
    CREATE NONCLUSTERED INDEX [IX_TRUPIMAGAZINA_ART_MAG_DATA] ON dbo.[T_TRUPIMAGAZINA] ([IDARTIKULL], [IDMAG], [DATA], [IDSTATUSDOK]) INCLUDE ([VLEFTA], [SHENJA], [IDRENDITJES], [IDKOKAMAGAZINA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_TRUPIMAGAZINA_IDARTIKULL_IDMAG_DATA')
    CREATE NONCLUSTERED INDEX [IX_TRUPIMAGAZINA_IDARTIKULL_IDMAG_DATA] ON dbo.[T_TRUPIMAGAZINA] ([IDARTIKULL], [IDMAG], [DATA]) INCLUDE ([IDTRUPIMAGAZINA], [IDKOKAMAGAZINA], [SASIA], [KOEFICENTI], [IDSTATUSDOK]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPIMAGAZINA') AND name = N'IX_TrupiMagazina_Koka_Art_Mag')
    CREATE NONCLUSTERED INDEX [IX_TrupiMagazina_Koka_Art_Mag] ON dbo.[T_TRUPIMAGAZINA] ([IDKOKAMAGAZINA], [IDARTIKULL], [IDMAG], [IDSTATUSDOK]) INCLUDE ([KOEFICENTI], [SASIA]);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_TRUPISHITJE') AND name = N'idx_ttrupishitje_IDSHITJEKOKA')
    CREATE NONCLUSTERED INDEX [idx_ttrupishitje_IDSHITJEKOKA] ON dbo.[T_TRUPISHITJE] ([IDSHITJEKOKA]);
