-- 05 - Eksporti i dokumenteve te magazines (Eksport.aspx, kategoria 6)
--
-- prc_T_KOKAMAGAZINA_merrDokMagazineSipasNdermarrjePerEksport per nje vit te klientit (1,5 milion rreshta magazine):
--   - llogariste te 56 kolonat, kurse Eksport.aspx shfaq vetem ato te formatit (~12);
--   - bashkonte cdo rresht me te gjithe tabelen e rreshtave te magazines (DESTINACION) dhe pastaj
--     GROUP BY mbi te 56 kolonat vetem per te hequr dublikatat qe mund te krijonte ai bashkim.
--   ~2 minuta vetem ne SQL.
--
-- Tani (per LLOJI = 1, eksporti ne skedar):
--   - DESTINACION dhe serialet merren te pa-dublikuara (DISTINCT) para bashkimit: dublikatat qe hiqte GROUP BY
--     vinin vetem nga keto dy bashkime (te gjitha te tjerat jane 1:1), keshtu qe rezultati eshte i njejte pa GROUP BY;
--   - parametri opsional @KOLONAT ('Kolona 1|Kolona 2|...'): llogariten vetem kolonat e kerkuara.
-- 1,5 milion rreshta: ~13 sekonda me kolonat e formatit. Pa @KOLONAT kthehen te gjitha kolonat si me pare.
-- LLOJI = 2 (eksporti ne tabela SQL) mbetet si me pare, vetem me DESTINACION te pa-dublikuar (GROUP BY e tij jep te njejtin rezultat).
-- AVEC e kontrollon vete nese procedura e ka @KOLONAT, keshtu qe radha e perditesimit (SQL/aplikacion) s'ka rendesi.
-- Rikthimi: 05-rollback-eksport-magazina.sql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[prc_T_KOKAMAGAZINA_merrDokMagazineSipasNdermarrjePerEksport]
(
	@IDNDERMARJE VARCHAR(100),
	@IDPERDORUES VARCHAR(100),
	@IDNDERVITI VARCHAR(100),
	@LLOJI INT,
	@EMERTABKOKA VARCHAR(100),
	@EMERFUSHEID VARCHAR(100),
	@SERIALEUNIKE bit,
	@IDPEREKSPORT VARCHAR(MAX),
	@KOLONAT VARCHAR(MAX) = NULL
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @Err INT
	DECLARE @SQL VARCHAR(MAX)

	-- Kolonat e rezultatit, ne rradhen e tyre (Serial NULL = gjithmone; 1/0 = sipas @SERIALEUNIKE)
	DECLARE @KOL TABLE (Rendi INT IDENTITY PRIMARY KEY, Alias VARCHAR(200), Expr VARCHAR(MAX), Serial BIT NULL)
	INSERT INTO @KOL (Alias, Expr, Serial) VALUES
	('Id Koka Magazina', 'T_KOKAMAGAZINA.IDKOKAMAGAZINA', NULL),
	('Nenkategoria', 'T_NIVELREGJISTRIMI.KODI', NULL),
	('Numer Projekti', 'T_KOKAMAGAZINA.NRPROJEKTI', NULL),
	('Lloj Dokumenti', 'T_KONFIGAMBJENTE.KODKONFIGAMBJENTE', NULL),
	('Klient/Furnitori', 'T_KLIENTFURNITOR.KODKLIENTFURNITOR', NULL),
	('Nr Dokumenti', 'T_KOKAMAGAZINA.NRDOK', NULL),
	('Kod Ndermarrje', 'T_NDERMARJE.NDERMARJEKODI', NULL),
	('Date Dokumenti', 'T_KOKAMAGAZINA.DTDOK', NULL),
	('Shenime', 'T_KOKAMAGAZINA.SHENIME', NULL),
	('Dege Administrative', 'T_DEGEADMINISTRATIVE.KODI', NULL),
	('Llogari', 'T_LLOGARI.NRLLOGARI', NULL),
	('Njesi Vartese', 'T_NJESIVARTESE.KODI', NULL),
	('Grupim Dok Magazine 1', 'GRUP1.KODI', NULL),
	('Grupim Dok Magazine 2', 'GRUP2.KODI', NULL),
	('Grupim Dok Magazine 3', 'GRUP3.KODI', NULL),
	('Magazinieri', 'T_KOKAMAGAZINA.MAGAZINIERI', NULL),
	('Pershkrimi', 'T_KOKAMAGAZINA.PERSHKRIMI', NULL),
	('Adresa', 'T_KOKAMAGAZINA.ADRESA', NULL),
	('Me Konfirmim', 'T_KOKAMAGAZINA.MEKONFIRMIM', NULL),
	('Id Nderm Vit', 'T_NDERMARJEVITI.VITI', NULL),
	('Krijuesi', 'T_PERDORUESI.PERDORUESUSERNAME', NULL),
	('Id Nivel Gjenerues', 'T_KOKAMAGAZINA.IDNIVELGJENERUES', NULL),
	('Id Konfig Gjenerues', 'T_KOKAMAGAZINA.IDKONFIGGJENERUES', NULL),
	('Id Gjenerues', 'T_KOKAMAGAZINA.IDGJENERUES', NULL),
	('Automjeti', 'autom.NRSHASIE', NULL),
	('Id Status Dok', 'T_KOKAMAGAZINA.IDSTATUSDOK', NULL),
	('Id Dok Nga', 'T_KOKAMAGAZINA.IDDOKNGA', NULL),
	('IdRreshtiMagazina', 'T_TRUPIMAGAZINA.IDTRUPIMAGAZINA', NULL),
	('Kodi i Artikullit', 'T_ARTIKULLI.KODARTIKULLI', NULL),
	('Njesia', 'T_NJESIARTIKULLI.KODNJESIA', NULL),
	('Sasia', 'T_TRUPIMAGAZINA.SASIA', NULL),
	('Cmimi', 'T_TRUPIMAGAZINA.CMIMI', NULL),
	('Vlefta', 'T_TRUPIMAGAZINA.VLEFTA', NULL),
	('Magazina', 'T_NJESIADMINISTRATIVE.KODI', NULL),
	('Detajimi 1', 'DET1.KODDETAJIMARTIKULLI', NULL),
	('Detajimi 2', 'DET2.KODDETAJIMARTIKULLI', NULL),
	('Mag destinacion', 'DESTINACION.MAGKODI', NULL),
	('Koeficenti', 'T_TRUPIMAGAZINA.KOEFICENTI', NULL),
	('Shenja', 'T_TRUPIMAGAZINA.SHENJA', NULL),
	('Sasi Progresive', 'T_TRUPIMAGAZINA.SASIAPROGRESIVE', NULL),
	('Vlefta Progresive', 'T_TRUPIMAGAZINA.VLEFTAPROGRESIVE', NULL),
	('Seriali', '''''', NULL),
	('IdTrupiKonvertimUD', 'T_TRUPIMAGAZINA.IDTRUPIKONVERTIMUD', NULL),
	('Shenime Trupi', 'T_TRUPIMAGAZINA.SHENIME', NULL),
	('Kodbari', 'CASE WHEN idkonf_merrSP.idkonfig IS NULL THEN T_KODBARI.PERSHKRIMI ELSE ISNULL(T_KODBARI.PERSHKRIMI, T_KODBARIPAREARTIKULLIT.PERSHKRIMI) END', NULL),
	('Numri Serial', 'T_KOKAMAGAZINA.NrSerial', NULL),
	('Artikulli Set', '[set].KODARTIKULLI', NULL),
	('WTNIC', 'T_KOKAMAGAZINA.WTNIC', NULL),
	('NIVFSH', 'T_KOKAMAGAZINA.NIVFSH', NULL),
	('SHOQERIMIKERKUAR', 'T_KOKAMAGAZINA.SHOQERIMIKERKUAR', NULL),
	('Transportuesi', 'T_KOKAMAGAZINA.Transportuesi', NULL),
	('IDOPERATOR', 'T_KOKAMAGAZINA.IDOPERATOR', NULL),
	('TIPI', 'T_KOKAMAGAZINA.TIPI', NULL),
	('TRANSAKSIONI', 'T_KOKAMAGAZINA.TRANSAKSIONI', NULL),
	('Seriali Unik Kryesor', 'slm.SERIALI_KRYESOR', 1),
	('Seriali Unik Dytesor', 'slm.SERIALI_DYTESOR', 1),
	('Seriali Unik Kryesor', '''''', 0),
	('Seriali Unik Dytesor', '''''', 0)

	DECLARE @COLS VARCHAR(MAX)
	SELECT @COLS = STRING_AGG(CAST(k.Expr + ' AS [' + k.Alias + ']' AS VARCHAR(MAX)), ', ') WITHIN GROUP (ORDER BY k.Rendi)
	FROM   @KOL k
	WHERE  (k.Serial IS NULL OR k.Serial = @SERIALEUNIKE)
	  AND  (@KOLONAT IS NULL OR @LLOJI <> 1
	        OR k.Alias IN ('Id Koka Magazina', 'IdRreshtiMagazina', 'Date Dokumenti')
	        OR k.Alias IN (SELECT LTRIM(RTRIM(value)) FROM STRING_SPLIT(@KOLONAT, '|')))

	SET @SQL = '
	CREATE TABLE #KONFIGNKAKNKA(idkonfig INT PRIMARY KEY)
	INSERT INTO #KONFIGNKAKNKA
	SELECT	DISTINCT idkonfig = t_konfigambjente.idkonfigambjente
	FROM	t_konfigambjente
			inner join t_kushtemplate on t_konfigambjente.idkonfigambjente = t_kushtemplate.idkonfigambjente
			inner join t_kushte on t_kushte.idkusht = t_kushtemplate.idkusht
			inner join t_alternativakushti on t_alternativakushti.IDALTERNATIVEKUSHTI = vlera and idkushti = t_kushte.idkusht
	WHERE	t_kushte.kodi = ''NKAKNKA''
			and idndermarje = ' + CONVERT(VARCHAR(MAX), @IDNDERMARJE) + '
			and alternativa = ''Po''
			AND IDSTATUSDOK = 1

	SELECT	' + @COLS + '
	FROM	T_KOKAMAGAZINA
			INNER JOIN T_TRUPIMAGAZINA ON T_KOKAMAGAZINA.IDKOKAMAGAZINA = T_TRUPIMAGAZINA.IDKOKAMAGAZINA
			INNER JOIN T_NIVELREGJISTRIMI ON T_KOKAMAGAZINA.IDNIVEL = T_NIVELREGJISTRIMI.IDNIVEL
			INNER JOIN T_KONFIGAMBJENTE ON T_KOKAMAGAZINA.IDKONFIGAMBJENTE = T_KONFIGAMBJENTE.IDKONFIGAMBJENTE
			INNER JOIN T_NDERMARJEVITI ON T_NDERMARJEVITI.IDNDERVITI = T_KOKAMAGAZINA.IDNDERMVIT '

	IF (@SERIALEUNIKE = 1)
		SET @SQL = @SQL + '
			LEFT JOIN (SELECT DISTINCT ID_TRUPI_MAGAZINE, SERIALI_KRYESOR, SERIALI_DYTESOR
			           FROM T_SERIALEUNIKE_LIDHJE_MAGAZINE) slm
				ON slm.ID_TRUPI_MAGAZINE = T_TRUPIMAGAZINA.IDTRUPIMAGAZINA '

	SET @SQL = @SQL + '
			LEFT JOIN T_KODBARI ON T_TRUPIMAGAZINA.IDBARKODI = T_KODBARI.IDKODBARI
			LEFT JOIN #KONFIGNKAKNKA idkonf_merrSP ON T_KOKAMAGAZINA.IDKONFIGAMBJENTE = idkonf_merrSP.idkonfig
			LEFT JOIN T_KLIENTFURNITOR ON T_KOKAMAGAZINA.IDKLIENTFURNITOR = T_KLIENTFURNITOR.IDKLIENTFURNITOR
			LEFT JOIN T_DEGEADMINISTRATIVE ON T_KOKAMAGAZINA.IDDEGEADMINISTRATIVE = T_DEGEADMINISTRATIVE.IDDEGEADMINISTRATIVE
			LEFT JOIN T_LLOGARI ON T_KOKAMAGAZINA.IDLLOG = T_LLOGARI.IDLLOGARI
			LEFT JOIN T_NJESIVARTESE ON T_KOKAMAGAZINA.IDNJESIVARTESE = T_NJESIVARTESE.IDNJESIVARTESE
			LEFT JOIN T_GRUPIMDOKUMENTIKOKA AS GRUP1 ON T_KOKAMAGAZINA.IDGRUP1 = GRUP1.IDGRUPIMKOKA
			LEFT JOIN T_GRUPIMDOKUMENTIKOKA AS GRUP2 ON T_KOKAMAGAZINA.IDGRUP2 = GRUP2.IDGRUPIMKOKA
			LEFT JOIN T_GRUPIMDOKUMENTIKOKA AS GRUP3 ON T_KOKAMAGAZINA.IDGRUP3 = GRUP3.IDGRUPIMKOKA
			LEFT JOIN T_ARTIKULLI ON T_TRUPIMAGAZINA.IDARTIKULL = T_ARTIKULLI.IDARTIKULLI
			LEFT JOIN T_ARTIKULLI [set] ON T_TRUPIMAGAZINA.IDARTIKULLSET = [set].IDARTIKULLI
			LEFT JOIN T_NJESIARTIKULLI ON T_TRUPIMAGAZINA.IDNJESIA = T_NJESIARTIKULLI.IDNJESIA
			LEFT JOIN T_NJESIADMINISTRATIVE ON T_NJESIADMINISTRATIVE.IDNJESIADM = T_TRUPIMAGAZINA.IDMAG
			LEFT JOIN T_DETAJIMARTIKULLI AS DET1 ON T_TRUPIMAGAZINA.IDDETAJIMI = DET1.IDDETAJIMARTIKULLI
			LEFT JOIN T_DETAJIMARTIKULLI AS DET2 ON T_TRUPIMAGAZINA.IDDETAJIMI2 = DET2.IDDETAJIMARTIKULLI
			LEFT JOIN T_PERDORUESI ON T_KOKAMAGAZINA.IDKRIJUESI = T_PERDORUESI.IDPERDORUES
			LEFT JOIN T_NDERMARJE ON T_KOKAMAGAZINA.IDNDERM = T_NDERMARJE.IDNDERMARJE
			LEFT JOIN T_AUTOMJETE AS autom ON autom.IDAUTOMJETI = T_KOKAMAGAZINA.IDAUTOMJETI
			-- magazina e destinacionit (dokumenti i gjeneruar nga ky): nje rresht per cdo kod magazine te ndryshem,
			-- aq sa linte GROUP BY i meparshem
			LEFT JOIN (SELECT DISTINCT K.IDGJENERUES, K.IDKONFIGGJENERUES, T.IDARTIKULL, T.IDTRUPIMAGAZINAOLD, MAGDEST.KODI AS MAGKODI
			           FROM   dbo.T_KOKAMAGAZINA K
			                  INNER JOIN dbo.T_TRUPIMAGAZINA T ON K.IDKOKAMAGAZINA = T.IDKOKAMAGAZINA
			                  LEFT JOIN dbo.T_NJESIADMINISTRATIVE MAGDEST ON T.IDMAG = MAGDEST.IDNJESIADM
			           WHERE  K.IDGJENERUES IS NOT NULL) AS DESTINACION
				ON	T_KOKAMAGAZINA.IDKOKAMAGAZINA = DESTINACION.IDGJENERUES
				AND T_KOKAMAGAZINA.IDKONFIGAMBJENTE = DESTINACION.IDKONFIGGJENERUES
				AND T_TRUPIMAGAZINA.IDARTIKULL = DESTINACION.IDARTIKULL
				AND DESTINACION.IDTRUPIMAGAZINAOLD = T_TRUPIMAGAZINA.IDTRUPIMAGAZINAOLD
			OUTER APPLY (SELECT TOP(1) PERSHKRIMI FROM T_KODBARI
			             WHERE IDARTIKULLI = T_ARTIKULLI.IDARTIKULLI
			               AND NJESIA = (CASE WHEN T_TRUPIMAGAZINA.IDNJESIA = T_ARTIKULLI.NJESI1ARTIKULLI THEN 1 ELSE 2 END)
			             ORDER BY IDKODBARI ASC) AS T_KODBARIPAREARTIKULLIT
	WHERE	T_KOKAMAGAZINA.IDNDERMVIT = ' + @IDNDERVITI + '
			AND T_KOKAMAGAZINA.IDNDERM = ' + @IDNDERMARJE + '
			AND T_KOKAMAGAZINA.IDSTATUSDOK = 1
			AND (T_KOKAMAGAZINA.IDKONFIGAMBJENTE IN (SELECT IDLIDHESE FROM T_LIDHJEAUTORIZIM WHERE IDAUTORIZIMEKOKA
					IN (SELECT IDAUTORIZIMKOKA FROM T_AUTORIZIMTRUPI WHERE IDPERDORUESI = ' + @IDPERDORUES + ') AND T_LIDHJEAUTORIZIM.idstatusdok = 1
					AND IDLLOJI IN (SELECT idllojbuxheti FROM T_LLOJBUXHETI WHERE KODLLOJBUXHETI = ''KonfigurimDok''))
				OR T_KOKAMAGAZINA.IDKONFIGAMBJENTE NOT IN (SELECT idlidhese FROM T_LIDHJEAUTORIZIM WHERE T_LIDHJEAUTORIZIM.idstatusdok = 1 AND IDLLOJI
					IN (SELECT idllojbuxheti FROM T_LLOJBUXHETI WHERE KODLLOJBUXHETI = ''KonfigurimDok''))) '

	IF (@IDPEREKSPORT <> '')
		SET @SQL = @SQL + ' AND T_KOKAMAGAZINA.IDKOKAMAGAZINA IN ( ' + @IDPEREKSPORT + ') '

	IF (@LLOJI = 1)
		-- pa GROUP BY: dublikatat i hiqte vetem ai, dhe tani DESTINACION/serialet vijne te pa-dublikuar
		SET @SQL = @SQL + '
	ORDER BY T_KOKAMAGAZINA.DTDOK DESC, T_KOKAMAGAZINA.IDKOKAMAGAZINA DESC'
	ELSE
	BEGIN
		SET @SQL = @SQL + '
		AND T_KOKAMAGAZINA.IDKOKAMAGAZINA NOT IN (SELECT [' + @EMERFUSHEID + '] FROM ' + @EMERTABKOKA + ')
		AND T_KOKAMAGAZINA.IDDOKNGA IS NULL
		GROUP BY T_KOKAMAGAZINA.IDKOKAMAGAZINA, T_TRUPIMAGAZINA.IDTRUPIMAGAZINA, T_KOKAMAGAZINA.NRPROJEKTI, T_NIVELREGJISTRIMI.KODI, T_KONFIGAMBJENTE.KODKONFIGAMBJENTE, T_KLIENTFURNITOR.KODKLIENTFURNITOR, T_KOKAMAGAZINA.NRDOK,
		 T_KOKAMAGAZINA.DTDOK, T_KOKAMAGAZINA.SHENIME, T_DEGEADMINISTRATIVE.KODI, T_LLOGARI.NRLLOGARI, T_NJESIADMINISTRATIVE.KODI, T_NJESIVARTESE.KODI, GRUP1.KODI, GRUP2.KODI, GRUP3.KODI, T_KOKAMAGAZINA.MAGAZINIERI,
		 T_KOKAMAGAZINA.PERSHKRIMI, T_KOKAMAGAZINA.ADRESA, T_ARTIKULLI.KODARTIKULLI, T_NJESIARTIKULLI.KODNJESIA, DET1.KODDETAJIMARTIKULLI, DET2.KODDETAJIMARTIKULLI, DESTINACION.MAGKODI, T_TRUPIMAGAZINA.SASIA, T_TRUPIMAGAZINA.CMIMI,
		 T_TRUPIMAGAZINA.VLEFTA, T_KOKAMAGAZINA.MEKONFIRMIM, T_NDERMARJEVITI.VITI, T_PERDORUESI.PERDORUESUSERNAME, T_KOKAMAGAZINA.IDNIVELGJENERUES, T_KOKAMAGAZINA.IDKONFIGGJENERUES, T_KOKAMAGAZINA.IDGJENERUES,
		 T_TRUPIMAGAZINA.KOEFICENTI, T_TRUPIMAGAZINA.SHENJA, T_TRUPIMAGAZINA.SASIAPROGRESIVE, T_TRUPIMAGAZINA.VLEFTAPROGRESIVE, T_NDERMARJE.NDERMARJEKODI, autom.NRSHASIE, T_KOKAMAGAZINA.IDSTATUSDOK, T_KOKAMAGAZINA.IDDOKNGA,
		 T_TRUPIMAGAZINA.IDTRUPIKONVERTIMUD, T_TRUPIMAGAZINA.SHENIME, T_KODBARI.PERSHKRIMI, T_KOKAMAGAZINA.NrSerial, [set].KODARTIKULLI, T_KODBARIPAREARTIKULLIT.PERSHKRIMI, idkonf_merrSP.idkonfig, T_KOKAMAGAZINA.WTNIC,
		 T_KOKAMAGAZINA.NIVFSH, T_KOKAMAGAZINA.SHOQERIMIKERKUAR, T_KOKAMAGAZINA.IDOPERATOR'
		IF (@SERIALEUNIKE = 1)
			SET @SQL = @SQL + ', slm.SERIALI_KRYESOR, slm.SERIALI_DYTESOR'
		SET @SQL = @SQL + ' ORDER BY T_KOKAMAGAZINA.DTDOK DESC, T_KOKAMAGAZINA.IDKOKAMAGAZINA DESC '
	END

	EXEC (@SQL)
	SET @Err = @@Error

	RETURN @Err
END
GO
