-- Rikthen versionin e meparshem (para 05-eksport-magazina.sql).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[prc_T_KOKAMAGAZINA_merrDokMagazineSipasNdermarrjePerEksport]
(
	@IDNDERMARJE VARCHAR(100),
	@IDPERDORUES VARCHAR(100),
	@IDNDERVITI VARCHAR(100),
	@LLOJI INT,
	@EMERTABKOKA VARCHAR(100),
	@EMERFUSHEID VARCHAR(100),
	@SERIALEUNIKE bit,
	@IDPEREKSPORT VARCHAR(MAX)
)
AS
BEGIN
	
DECLARE @Err Int
DECLARE @SQL1 VARCHAR(MAX)
DECLARE @SQL2 VARCHAR(MAX)
DECLARE @SQL3 VARCHAR(MAX)

SET @SQL1= '
    CREATE TABLE #KONFIGNKAKNKA(idkonfig INT PRIMARY KEY)
			INSERT INTO #KONFIGNKAKNKA
			SELECT	DISTINCT idkonfig = t_konfigambjente.idkonfigambjente 
			FROM	t_konfigambjente 
					inner join t_kushtemplate 
						on t_konfigambjente.idkonfigambjente=t_kushtemplate.idkonfigambjente 
					inner join t_kushte 
						on t_kushte.idkusht=t_kushtemplate.idkusht 
					inner join t_alternativakushti 
						on t_alternativakushti.IDALTERNATIVEKUSHTI=vlera and idkushti=t_kushte.idkusht 
			WHERE	t_kushte.kodi = ''NKAKNKA'' 
					and idndermarje = ' + convert(varchar(MAX), @IDNDERMARJE) + ' 
					and alternativa = ''Po'' 
					AND IDSTATUSDOK = 1

	SELECT	T_KOKAMAGAZINA.IDKOKAMAGAZINA AS [Id Koka Magazina]
			,T_NIVELREGJISTRIMI.KODI AS Nenkategoria
			,T_KOKAMAGAZINA.NRPROJEKTI AS [Numer Projekti]
			,T_KONFIGAMBJENTE.KODKONFIGAMBJENTE AS [Lloj Dokumenti]
			,T_KLIENTFURNITOR.KODKLIENTFURNITOR AS [Klient/Furnitori]
			,T_KOKAMAGAZINA.NRDOK AS [Nr Dokumenti]
			,T_NDERMARJE.NDERMARJEKODI AS [Kod Ndermarrje]
			,T_KOKAMAGAZINA.DTDOK AS [Date Dokumenti]
			,T_KOKAMAGAZINA.SHENIME AS Shenime
			,T_DEGEADMINISTRATIVE.KODI AS [Dege Administrative]
			,T_LLOGARI.NRLLOGARI AS Llogari
			,T_NJESIVARTESE.KODI AS [Njesi Vartese]
			,GRUP1.KODI AS [Grupim Dok Magazine 1]
			,GRUP2.KODI AS [Grupim Dok Magazine 2]
			,GRUP3.KODI AS [Grupim Dok Magazine 3]
			,T_KOKAMAGAZINA.MAGAZINIERI as Magazinieri
			,T_KOKAMAGAZINA.PERSHKRIMI as Pershkrimi
			,T_KOKAMAGAZINA.ADRESA as Adresa
			,T_KOKAMAGAZINA.MEKONFIRMIM AS [Me Konfirmim]
			,T_NDERMARJEVITI.VITI as [Id Nderm Vit]
			,T_PERDORUESI.PERDORUESUSERNAME AS Krijuesi
			,T_KOKAMAGAZINA.IDNIVELGJENERUES as [Id Nivel Gjenerues]
			,T_KOKAMAGAZINA.IDKONFIGGJENERUES AS [Id Konfig Gjenerues]
			,T_KOKAMAGAZINA.IDGJENERUES AS [Id Gjenerues]
			,autom.NRSHASIE as Automjeti
			,T_KOKAMAGAZINA.IDSTATUSDOK AS [Id Status Dok]
			,T_KOKAMAGAZINA.IDDOKNGA as [Id Dok Nga]
			,dbo.T_TRUPIMAGAZINA.IDTRUPIMAGAZINA AS IdRreshtiMagazina
			,T_ARTIKULLI.KODARTIKULLI AS [Kodi i Artikullit]
			,dbo.T_NJESIARTIKULLI.KODNJESIA AS Njesia
			,dbo.T_TRUPIMAGAZINA.SASIA AS Sasia
			,dbo.T_TRUPIMAGAZINA.CMIMI AS Cmimi
			,dbo.T_TRUPIMAGAZINA.VLEFTA AS Vlefta
			,dbo.T_NJESIADMINISTRATIVE.KODI AS Magazina
			,DET1.KODDETAJIMARTIKULLI AS [Detajimi 1]
			,DET2.KODDETAJIMARTIKULLI AS [Detajimi 2]
			,MAGDEST.KODI AS [Mag destinacion]
			,T_TRUPIMAGAZINA.KOEFICENTI as [Koeficenti]
			,T_TRUPIMAGAZINA.SHENJA as [Shenja]
			,T_TRUPIMAGAZINA.SASIAPROGRESIVE as [Sasi Progresive]
			,T_TRUPIMAGAZINA.VLEFTAPROGRESIVE as [Vlefta Progresive]
			,'''' AS Seriali
			,T_TRUPIMAGAZINA.IDTRUPIKONVERTIMUD AS IdTrupiKonvertimUD
			,T_TRUPIMAGAZINA.SHENIME AS [Shenime Trupi]
			,CASE WHEN idkonf_merrSP.idkonfig IS NULL THEN T_KODBARI.PERSHKRIMI ELSE  
			 ISNULL(T_KODBARI.PERSHKRIMI, T_KODBARIPAREARTIKULLIT.PERSHKRIMI) END as Kodbari
			,T_KOKAMAGAZINA.NrSerial as [Numri Serial]
			,[set].KODARTIKULLI AS [Artikulli Set],
			T_KOKAMAGAZINA.WTNIC,
			T_KOKAMAGAZINA.NIVFSH,
			T_KOKAMAGAZINA.SHOQERIMIKERKUAR,
			T_KOKAMAGAZINA.Transportuesi,
			T_KOKAMAGAZINA.IDOPERATOR,
			T_KOKAMAGAZINA.TIPI,
			T_KOKAMAGAZINA.TRANSAKSIONI'

IF(@SERIALEUNIKE = 1)
	SET @SQL1 = @SQL1 + ', slm.SERIALI_KRYESOR [Seriali Unik Kryesor],slm.SERIALI_DYTESOR [Seriali Unik Dytesor]'
else
	SET  @SQL1 = @SQL1 + ', '''' [Seriali Unik Kryesor],'''' [Seriali Unik Dytesor]'

SET @SQL1 = @SQL1 + '
	FROM	T_KOKAMAGAZINA
			INNER JOIN T_TRUPIMAGAZINA ON T_KOKAMAGAZINA.IDKOKAMAGAZINA = T_TRUPIMAGAZINA.IDKOKAMAGAZINA
			INNER JOIN T_NIVELREGJISTRIMI ON T_KOKAMAGAZINA.IDNIVEL=T_NIVELREGJISTRIMI.IDNIVEL
			INNER JOIN T_KONFIGAMBJENTE ON T_KOKAMAGAZINA.IDKONFIGAMBJENTE=T_KONFIGAMBJENTE.IDKONFIGAMBJENTE
			INNER JOIN	T_NDERMARJEVITI ON T_NDERMARJEVITI.IDNDERVITI=T_KOKAMAGAZINA.IDNDERMVIT '
	
IF(@SERIALEUNIKE = 1)
	SET @SQL1 = @SQL1 +	'
			LEFT JOIN T_SERIALEUNIKE_LIDHJE_MAGAZINE slm 
				on slm.id_trupi_magazine = T_TRUPIMAGAZINA.idtrupimagazina '

SET @SQL1 = @SQL1 +	'
			LEFT JOIN	T_KODBARI ON T_TRUPIMAGAZINA.IDBARKODI = T_KODBARI.IDKODBARI
			LEFT JOIN #KONFIGNKAKNKA idkonf_merrSP ON T_KOKAMAGAZINA.IDKONFIGAMBJENTE =idkonf_merrSP.idkonfig
			LEFT JOIN	T_KLIENTFURNITOR ON T_KOKAMAGAZINA.IDKLIENTFURNITOR=T_KLIENTFURNITOR.IDKLIENTFURNITOR
			LEFT JOIN	T_DEGEADMINISTRATIVE ON T_KOKAMAGAZINA.IDDEGEADMINISTRATIVE=T_DEGEADMINISTRATIVE.IDDEGEADMINISTRATIVE
			LEFT JOIN	T_LLOGARI ON T_KOKAMAGAZINA.IDLLOG=T_LLOGARI.IDLLOGARI
			LEFT JOIN	T_NJESIVARTESE ON T_KOKAMAGAZINA.IDNJESIVARTESE=T_NJESIVARTESE.IDNJESIVARTESE
			LEFT JOIN	T_GRUPIMDOKUMENTIKOKA AS GRUP1 ON T_KOKAMAGAZINA.IDGRUP1=GRUP1.IDGRUPIMKOKA
			LEFT JOIN	T_GRUPIMDOKUMENTIKOKA AS GRUP2 ON T_KOKAMAGAZINA.IDGRUP2=GRUP2.IDGRUPIMKOKA
			LEFT JOIN	T_GRUPIMDOKUMENTIKOKA AS GRUP3 ON T_KOKAMAGAZINA.IDGRUP3=GRUP3.IDGRUPIMKOKA
			LEFT JOIN	T_ARTIKULLI ON T_TRUPIMAGAZINA.IDARTIKULL=T_ARTIKULLI.IDARTIKULLI
			LEFT JOIN	T_ARTIKULLI [set] ON T_TRUPIMAGAZINA.IDARTIKULLSET=[set].IDARTIKULLI
			LEFT JOIN	T_NJESIARTIKULLI ON T_TRUPIMAGAZINA.IDNJESIA=T_NJESIARTIKULLI.IDNJESIA
			LEFT JOIN	T_NJESIADMINISTRATIVE ON T_NJESIADMINISTRATIVE.IDNJESIADM=T_TRUPIMAGAZINA.IDMAG
			LEFT JOIN	T_DETAJIMARTIKULLI AS DET1 ON T_TRUPIMAGAZINA.IDDETAJIMI=DET1.IDDETAJIMARTIKULLI
			LEFT JOIN	T_DETAJIMARTIKULLI AS DET2 ON T_TRUPIMAGAZINA.IDDETAJIMI2=DET2.IDDETAJIMARTIKULLI
			LEFT JOIN	T_PERDORUESI ON T_KOKAMAGAZINA.IDKRIJUESI=T_PERDORUESI.IDPERDORUES
			LEFT JOIN	T_NDERMARJE ON T_KOKAMAGAZINA.IDNDERM=T_NDERMARJE.IDNDERMARJE
			LEFT JOIN	T_AUTOMJETE as autom ON autom.IDAUTOMJETI = T_KOKAMAGAZINA.IDAUTOMJETI
			LEFT JOIN	( SELECT	K.IDGJENERUES
									,IDKONFIGGJENERUES
									,T.IDMAG
									,T.IDARTIKULL
									,T.IDTRUPIMAGAZINAOLD
							FROM	dbo.T_KOKAMAGAZINA K
									INNER JOIN dbo.T_TRUPIMAGAZINA T 
										ON K.IDKOKAMAGAZINA = T.IDKOKAMAGAZINA
						)	AS DESTINACION 
				ON	T_KOKAMAGAZINA.IDKOKAMAGAZINA=DESTINACION.IDGJENERUES 
					AND T_KOKAMAGAZINA.IDKONFIGAMBJENTE = DESTINACION.IDKONFIGGJENERUES
					AND T_TRUPIMAGAZINA.IDARTIKULL = DESTINACION.IDARTIKULL
					AND DESTINACION.IDTRUPIMAGAZINAOLD = dbo.T_TRUPIMAGAZINA.IDTRUPIMAGAZINAOLD
			LEFT JOIN	dbo.T_NJESIADMINISTRATIVE MAGDEST 
				ON DESTINACION.IDMAG = MAGDEST.IDNJESIADM
				OUTER APPLY (SELECT TOP(1) * FROM T_KODBARI
				 WHERE IDARTIKULLI = T_ARTIKULLI.IDARTIKULLI AND NJESIA = (CASE WHEN T_TRUPIMAGAZINA.IDNJESIA = T_ARTIKULLI.NJESI1ARTIKULLI THEN 1 ELSE 2 END)
				 ORDER BY IDKODBARI ASC
				) AS T_KODBARIPAREARTIKULLIT
	WHERE	T_KOKAMAGAZINA.IDNDERMVIT = ' + @IDNDERVITI + ' 
			AND dbo.T_KOKAMAGAZINA.IDNDERM = ' + @IDNDERMARJE + '
			AND T_KOKAMAGAZINA.IDSTATUSDOK = 1 
			and (T_KOKAMAGAZINA.IDKONFIGAMBJENTE in (select IDLIDHESE from T_LIDHJEAUTORIZIM where IDAUTORIZIMEKOKA  
            IN (select IDAUTORIZIMKOKA from T_AUTORIZIMTRUPI  where IDPERDORUESI =' + @IDPERDORUES + ' )  and T_LIDHJEAUTORIZIM.idstatusdok=1
            and IDLLOJI in (select idllojbuxheti from T_LLOJBUXHETI  where KODLLOJBUXHETI=''KonfigurimDok''))
            or T_KOKAMAGAZINA.IDKONFIGAMBJENTE  not in (select idlidhese from T_LIDHJEAUTORIZIM where T_LIDHJEAUTORIZIM.idstatusdok=1 and  IDLLOJI 
            in (select idllojbuxheti from T_LLOJBUXHETI  where KODLLOJBUXHETI=''KonfigurimDok''))) '

IF(@IDPEREKSPORT <> '')
	SET @SQL2 = ' AND T_KOKAMAGAZINA.IDKOKAMAGAZINA IN ( ' + @IDPEREKSPORT + ') '


IF(@LLOJI = 1)
   BEGIN
	 SET @SQL3 = 'GROUP BY T_KOKAMAGAZINA.IDKOKAMAGAZINA, T_TRUPIMAGAZINA.IDTRUPIMAGAZINA, T_KOKAMAGAZINA.NRPROJEKTI, T_NIVELREGJISTRIMI.KODI, T_KONFIGAMBJENTE.KODKONFIGAMBJENTE, T_KLIENTFURNITOR.KODKLIENTFURNITOR, 
	  T_KOKAMAGAZINA.NRDOK, T_KOKAMAGAZINA.DTDOK, T_KOKAMAGAZINA.SHENIME, T_DEGEADMINISTRATIVE.KODI, T_LLOGARI.NRLLOGARI, T_NJESIADMINISTRATIVE.KODI, T_NJESIVARTESE.KODI, GRUP1.KODI, GRUP2.KODI, GRUP3.KODI, T_KOKAMAGAZINA.MAGAZINIERI,
	  T_KOKAMAGAZINA.PERSHKRIMI, T_KOKAMAGAZINA.ADRESA, T_ARTIKULLI.KODARTIKULLI, T_NJESIARTIKULLI.KODNJESIA, DET1.KODDETAJIMARTIKULLI, DET2.KODDETAJIMARTIKULLI, MAGDEST.KODI, T_TRUPIMAGAZINA.SASIA, T_TRUPIMAGAZINA.CMIMI, 
	  T_TRUPIMAGAZINA.VLEFTA, T_KOKAMAGAZINA.MEKONFIRMIM, T_NDERMARJEVITI.VITI, T_PERDORUESI.PERDORUESUSERNAME, T_KOKAMAGAZINA.IDNIVELGJENERUES, T_KOKAMAGAZINA.IDKONFIGGJENERUES, T_KOKAMAGAZINA.IDGJENERUES, T_TRUPIMAGAZINA.KOEFICENTI,
	  T_TRUPIMAGAZINA.SHENJA, T_TRUPIMAGAZINA.SASIAPROGRESIVE, T_TRUPIMAGAZINA.VLEFTAPROGRESIVE, T_NDERMARJE.NDERMARJEKODI, autom.NRSHASIE, T_KOKAMAGAZINA.IDSTATUSDOK,T_KOKAMAGAZINA.IDDOKNGA, T_TRUPIMAGAZINA.IDTRUPIKONVERTIMUD, 
	  T_TRUPIMAGAZINA.SHENIME, T_KODBARI.PERSHKRIMI, T_KOKAMAGAZINA.NrSerial, [set].KODARTIKULLI, T_KODBARIPAREARTIKULLIT.PERSHKRIMI, idkonf_merrSP.idkonfig, T_KOKAMAGAZINA.WTNIC, T_KOKAMAGAZINA.NIVFSH,T_KOKAMAGAZINA.SHOQERIMIKERKUAR,T_KOKAMAGAZINA.Transportuesi, T_KOKAMAGAZINA.IDOPERATOR, T_KOKAMAGAZINA.TIPI, T_KOKAMAGAZINA.TRANSAKSIONI '
	 
	 IF(@SERIALEUNIKE = 1)
	 SET @SQL3 = @SQL3 +	',slm.SERIALI_KRYESOR,slm.SERIALI_DYTESOR'
	 	SET @SQL3 = @SQL3 +	'
	 		ORDER BY T_KOKAMAGAZINA.DTDOK DESC, dbo.T_KOKAMAGAZINA.idkokamagazina DESC'
   END
ELSE
   BEGIN
   	SET @SQL3 = '
   		AND T_KOKAMAGAZINA.IDKOKAMAGAZINA NOT IN (SELECT [' + @EMERFUSHEID + '] FROM ' + @EMERTABKOKA + ') 
   		AND T_KOKAMAGAZINA.IDDOKNGA IS NULL
   		GROUP BY T_KOKAMAGAZINA.IDKOKAMAGAZINA, T_TRUPIMAGAZINA.IDTRUPIMAGAZINA, T_KOKAMAGAZINA.NRPROJEKTI, T_NIVELREGJISTRIMI.KODI, T_KONFIGAMBJENTE.KODKONFIGAMBJENTE, T_KLIENTFURNITOR.KODKLIENTFURNITOR, T_KOKAMAGAZINA.NRDOK,
   		 T_KOKAMAGAZINA.DTDOK, T_KOKAMAGAZINA.SHENIME, T_DEGEADMINISTRATIVE.KODI, T_LLOGARI.NRLLOGARI, T_NJESIADMINISTRATIVE.KODI, T_NJESIVARTESE.KODI, GRUP1.KODI, GRUP2.KODI, GRUP3.KODI, T_KOKAMAGAZINA.MAGAZINIERI, 
   		 T_KOKAMAGAZINA.PERSHKRIMI, T_KOKAMAGAZINA.ADRESA, T_ARTIKULLI.KODARTIKULLI, T_NJESIARTIKULLI.KODNJESIA, DET1.KODDETAJIMARTIKULLI, DET2.KODDETAJIMARTIKULLI, MAGDEST.KODI, T_TRUPIMAGAZINA.SASIA, T_TRUPIMAGAZINA.CMIMI,
   		 T_TRUPIMAGAZINA.VLEFTA, T_KOKAMAGAZINA.MEKONFIRMIM, T_NDERMARJEVITI.VITI, T_PERDORUESI.PERDORUESUSERNAME, T_KOKAMAGAZINA.IDNIVELGJENERUES, T_KOKAMAGAZINA.IDKONFIGGJENERUES, T_KOKAMAGAZINA.IDGJENERUES,
   		 T_TRUPIMAGAZINA.KOEFICENTI, T_TRUPIMAGAZINA.SHENJA, T_TRUPIMAGAZINA.SASIAPROGRESIVE, T_TRUPIMAGAZINA.VLEFTAPROGRESIVE, T_NDERMARJE.NDERMARJEKODI, autom.NRSHASIE, T_KOKAMAGAZINA.IDSTATUSDOK,T_KOKAMAGAZINA.IDDOKNGA,
   		 T_TRUPIMAGAZINA.IDTRUPIKONVERTIMUD, T_TRUPIMAGAZINA.SHENIME, T_KODBARI.PERSHKRIMI, T_KOKAMAGAZINA.NrSerial, [set].KODARTIKULLI, T_KODBARIPAREARTIKULLIT.PERSHKRIMI, idkonf_merrSP.idkonfig, T_KOKAMAGAZINA.WTNIC,
   		 T_KOKAMAGAZINA.NIVFSH, T_KOKAMAGAZINA.SHOQERIMIKERKUAR,T_KOKAMAGAZINA.IDOPERATOR'
   	
   	IF(@SERIALEUNIKE = 1)
   	SET @SQL3 = @SQL3 +	',slm.SERIALI_KRYESOR,slm.SERIALI_DYTESOR'
   		SET @SQL3 = @SQL3 +	' ORDER BY T_KOKAMAGAZINA.DTDOK DESC, dbo.T_KOKAMAGAZINA.idkokamagazina DESC '
   END	

	PRINT(@SQL1)
	PRINT(@SQL2)
	PRINT(@SQL3)
	EXEC (@SQL1+@SQL2+@SQL3) 
	SET @Err = @@Error

	RETURN @Err
END
GO
