-- 08 - Ruajtja e dokumenteve te magazines (edhe ne import)
--
-- 1. prc_T_KOKAMAGAZINA_ekzistonRegjistrimMagazineSipasIdentifikuesi (kontrolli i dokumentit te dublikuar, per cdo
--    dokument): filtrat "kolona = CASE WHEN ... ELSE kolona END" me nje plan te ruajtur skanonin T_KOKAMAGAZINA
--    (~60 ms). OPTION (RECOMPILE) + indeks (IDNDERM, NRDOK).
-- 2. prc_T_TRUPIMAGAZINA_ins_Dt: UPDATE qe rilidh IDTRUPIKONVERTIMUD te rreshtave te rinj skanonte te gjithe indeksin
--    e asaj kolone (~290 ms per dokument). OPTION (LOOP JOIN): kerkim me indeks per rreshtat e dokumentit. E njejta logjike.
-- Rikthimi: 08-rollback-ruajtje-magazine.sql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.T_KOKAMAGAZINA') AND name = N'IX_T_KOKAMAGAZINA_IDNDERM_NRDOK')
    CREATE NONCLUSTERED INDEX IX_T_KOKAMAGAZINA_IDNDERM_NRDOK ON dbo.T_KOKAMAGAZINA (IDNDERM, NRDOK);
GO
ALTER PROCEDURE [dbo].[prc_T_KOKAMAGAZINA_ekzistonRegjistrimMagazineSipasIdentifikuesi]
(
@IDKONFIGAMBJENTE T_FOR_KEY,
@NRDOK VARCHAR(100),
@IDMAG T_FOR_KEY,
@DTDOK T_DATE,
@IDNDERMARJE T_FOR_KEY,
@idnivel t_for_key,
@IDKLIENTFURNITOR t_for_key,
@IDDEGEADMINISTRATIVE t_for_key,
@IDRAPORTDESING t_for_key,
@IDGRUP1 t_for_key,
@IDGRUP2 t_for_key,
@IDGRUP3 t_for_key,
@IDKOKAMAGAZINA T_FOR_KEY

)
AS
BEGIN

DECLARE @Err Int
DECLARE @ident AS TABLE (kodkontroll varchar(100))
INSERT @ident

SELECT KODKONTROLL FROM dbo.T_ATRIBUTETRUPI ta INNER JOIN dbo.T_KONTROLLE tk ON tk.IDKONTROLL = ta.IDKONTROLL WHERE ta.IDKONFIGAMBJENTE=@IDKONFIGAMBJENTE AND tk.TIPI<>0  AND ta.UNIKE=1

	DECLARE @EXISTS1  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbLloji'),0)
	DECLARE @EXISTS2  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbKonfigurimi'),0)
	DECLARE @EXISTS3  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='dteDtDok'),0)
	DECLARE @EXISTS4  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='txtNrDok'),0)
	DECLARE @EXISTS5  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='btneKlientFurnitori'),0)
	DECLARE @EXISTS6  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='btneMagazina'),0)
	DECLARE @EXISTS7  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbDegeAdministrative'),0)
	DECLARE @EXISTS8  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbFormatiPrintimit'),0)
	DECLARE @EXISTS9  AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbGrup1'),0)
	DECLARE @EXISTS10 AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbGrup2'),0)
	DECLARE @EXISTS11 AS BIT = ISNULL((SELECT 1 FROM @ident i WHERE i.kodkontroll='cmbGrup3'),0)

if(SELECT count(*) FROM @ident i)=0
select 1;
	ELSE 

	select count(*)
	from T_KOKAMAGAZINA
	 WHERE IDSTATUSDOK in (1,0) AND dbo.T_KOKAMAGAZINA.IDNDERM=@IDNDERMARJE and IDKOKAMAGAZINA <> @IDKOKAMAGAZINA      
	AND dbo.T_KOKAMAGAZINA.IDNIVEL					=( CASE WHEN @EXISTS1 > 0 THEN @idnivel else idnivel END )       
	AND dbo.T_KOKAMAGAZINA.IDKONFIGAMBJENTE			=( CASE WHEN @EXISTS2 > 0 THEN @IDKONFIGAMBJENTE else IDKONFIGAMBJENTE END ) 
	AND dbo.T_KOKAMAGAZINA.DTDOK					=( CASE WHEN @EXISTS3 > 0 THEN @DTDOK else DTDOK END ) 
	AND dbo.T_KOKAMAGAZINA.NRDOK					=( CASE WHEN @EXISTS4 > 0  THEN @NRDOK else NRDOK END )
	AND (dbo.T_KOKAMAGAZINA.IDKLIENTFURNITOR		=( CASE WHEN @EXISTS5 > 0 THEN @IDKLIENTFURNITOR else IDKLIENTFURNITOR END ) OR ( dbo.T_KOKAMAGAZINA.IDKLIENTFURNITOR IS NULL AND @EXISTS5 = 0 ))
	AND (dbo.T_KOKAMAGAZINA.IDMAG					=( CASE WHEN @EXISTS6 > 0 THEN @IDMAG else IDMAG END ) OR ( dbo.T_KOKAMAGAZINA.IDMAG IS NULL AND @EXISTS6 = 0 ))
	AND (dbo.T_KOKAMAGAZINA.IDDEGEADMINISTRATIVE	=( CASE WHEN @EXISTS7 > 0 THEN @IDDEGEADMINISTRATIVE else IDDEGEADMINISTRATIVE END )OR (dbo.T_KOKAMAGAZINA.IDDEGEADMINISTRATIVE IS NULL AND @EXISTS7 = 0 ))
	AND( dbo.T_KOKAMAGAZINA.IDRAPORTDESING			=( CASE WHEN @EXISTS8 > 0 THEN @IDRAPORTDESING else IDRAPORTDESING END )OR (dbo.T_KOKAMAGAZINA.IDRAPORTDESING IS NULL AND @EXISTS8 = 0 ))
	AND (dbo.T_KOKAMAGAZINA.IDGRUP1					=( CASE WHEN @EXISTS9 > 0 THEN @IDGRUP1 else IDGRUP1 END ) OR (dbo.T_KOKAMAGAZINA.IDGRUP1 IS NULL AND @EXISTS9 = 0 ))
	AND (dbo.T_KOKAMAGAZINA.IDGRUP2					=( CASE WHEN @EXISTS10 > 0 THEN @IDGRUP2 else IDGRUP2 END ) OR (dbo.T_KOKAMAGAZINA.IDGRUP2 IS NULL AND @EXISTS10 = 0 ))
	AND (dbo.T_KOKAMAGAZINA.IDGRUP3					=( CASE WHEN @EXISTS11 > 0 THEN @IDGRUP3 else IDGRUP3 END ) OR (dbo.T_KOKAMAGAZINA.IDGRUP3 IS NULL AND @EXISTS11 = 0 ))
	-- plani per vlerat konkrete: pa te, filtrat "kolona = CASE ... ELSE kolona END" skanonin T_KOKAMAGAZINA ne cdo ruajtje
	OPTION (RECOMPILE)
               
	Set @Err = @@Error

	RETURN @Err
	
END
GO
ALTER PROCEDURE [dbo].[prc_T_TRUPIMAGAZINA_ins_Dt]
(
	@TRUPIMAG T_TRUPIMAGAZINA_type READONLY,
	@newIdRenditje bit,
	@isDalje bit
)
AS
BEGIN
declare @koefDalje int
declare @koefHyrje int
set @koefDalje = 1
set @koefHyrje = 10

DECLARE @TIMESTAMPFILLO datetime = GETDATE(); 
DECLARE @EXECTIME		datetime = GETDATE(); 

CREATE TABLE #TempTrupiIns(IDTRUPIMAGAZINA NUMERIC(18, 0) primary key, IDTRUPIMAGAZINA_OLD NUMERIC(18, 0), IDRENDITJES NUMERIC(18, 0), IDKOKAMAGAZINA NUMERIC(18, 0), idtrupikonvertimud NUMERIC(18, 0), IDTRUPIREZERVIMI NUMERIC(18, 0), idartikull NUMERIC(18, 0), idmag NUMERIC(18, 0), sasia float, shenja int, koeficenti float, data DATETIME, iddetajimi NUMERIC(18, 0), vlefta float, IDARTIKULLSET NUMERIC(18,0));

INSERT INTO [T_TRUPIMAGAZINA](IDKOKAMAGAZINA, IDLLOJVEPRIMI, IDARTIKULL, IDNJESIA, SASIA, VLEFTA, KOEFICENTI, SHENJA, SASIAPROGRESIVE, VLEFTAPROGRESIVE, IDMAG, DATA, IDSTATUSDOK, IDRENDITJES, IDDETAJIMI, SASIPROGRESIVEDETAJIMI, VLEFTEPROGRESIVEDETAJIMI, IDDETAJIMI2, IDTRUPIREZERVIMI, IDTRUPIKONVERTIMFSH, IDTRUPIKONVERTIMUSH, IDTRUPIKONVERTIMUD, IDKTHIMI, IDTRUPISHITJEGJENERIMI, SHENIME, IDTRUPIMAGAZINAOLD,IDARTIKULLSET, IDBARKODI)

OUTPUT inserted.IDTRUPIMAGAZINA, INSERTED.IDTRUPIMAGAZINAOLD, inserted.IDRENDITJES, inserted.IDKOKAMAGAZINA, inserted.IDTRUPIKONVERTIMUD, INSERTED.IDTRUPIREZERVIMI, INSERTED.IDARTIKULL, INSERTED.IDMAG, INSERTED.SASIA, INSERTED.SHENJA, INSERTED.KOEFICENTI, INSERTED.DATA, INSERTED.IDDETAJIMI, INSERTED.VLEFTA , INSERTED.IDARTIKULLSET

INTO #TempTrupiIns(IDTRUPIMAGAZINA , IDTRUPIMAGAZINA_OLD, IDRENDITJES, IDKOKAMAGAZINA , IDTRUPIKONVERTIMUD,IDTRUPIREZERVIMI,idartikull,idmag, sasia, shenja, KOEFICENTI,data, iddetajimi,vlefta, IDARTIKULLSET)

SELECT IDKOKAMAGAZINA, IDLLOJVEPRIMI, IDARTIKULL, IDNJESIA, SASIA, VLEFTA, KOEFICENTI, SHENJA, SASIAPROGRESIVE, VLEFTAPROGRESIVE, IDMAG, DATA, IDSTATUSDOK,
	CASE WHEN @newIdRenditje=1 THEN ROW_NUMBER() OVER (PARTITION BY tm.IDMAG ORDER BY tm.IDTRUPIMAGAZINA) ELSE IDRENDITJES END,
	CASE IDDETAJIMI  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDDETAJIMI END,
	SASIPROGRESIVEDETAJIMI, VLEFTEPROGRESIVEDETAJIMI,
	CASE IDDETAJIMI2 WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDDETAJIMI2 END,
	CASE IDTRUPIREZERVIMI  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDTRUPIREZERVIMI END,
	CASE IDTRUPIKONVERTIMFSH WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDTRUPIKONVERTIMFSH END,
	CASE IDTRUPIKONVERTIMUSH  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDTRUPIKONVERTIMUSH END,
	CASE IDTRUPIKONVERTIMUD  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDTRUPIKONVERTIMUD END,
	CASE IDKTHIMI  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDKTHIMI END,
	CASE IDTRUPISHITJEGJENERIMI  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDTRUPISHITJEGJENERIMI END,
	SHENIME, IDTRUPIMAGAZINA,CASE idartikullset  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE idartikullset END idartikullset,
	CASE IDBARKODI  WHEN 0 THEN NULL WHEN -1 THEN NULL ELSE IDBARKODI END IDBARKODI
FROM @TRUPIMAG tm 
ORDER BY tm.IDTRUPIMAGAZINA

PRINT 'INSERT PARE TEK T_TRUPIMAGAZINA : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()

UPDATE	rezi
SET		rezi.IDTRUPINGAVJEN = te_rejat.IDTRUPIMAGAZINA
FROM	T_TRUPIREZERVIME rezi
		JOIN #TempTrupiIns te_rejat	ON rezi.IDTRUPIREZERVIME = te_rejat.IDTRUPIREZERVIMI

PRINT 'UPDATE REZI : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()
	  
UPDATE	trupi
SET		IDTRUPIkonvertimUD = te_rejat.IDTRUPIMAGAZINA
FROM	[T_TRUPIMAGAZINA] trupi
		INNER JOIN	#TempTrupiIns te_rejat ON trupi.IDTRUPIKONVERTIMUD = te_rejat.IDTRUPIMAGAZINA_OLD
-- kerkim me indeks per rreshtat e rinj (disa) ne vend te skanimit te te gjithe indeksit (~9000 faqe per dokument)
OPTION (LOOP JOIN)

PRINT 'UPDATE TRUPI : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()
		
DECLARE @idndermarje int

SELECT	TOP 1 @idndermarje = tn.idndermarje 
FROM	T_NJESIADMINISTRATIVE tn 
		JOIN #TempTrupiIns ON TN.IDNJESIADM = #TempTrupiIns.idmag

PRINT 'SELECT @idndermarje : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()

CREATE table #KONFIGAMB  (ID NUMERIC(18, 0) PRIMARY KEY )
INSERT	INTO #KONFIGAMB
SELECT	DISTINCT T_KONFIGAMBJENTE.IDKONFIGAMBJENTE
FROM	T_KONFIGAMBJENTE 
		JOIN T_KUSHTEMPLATE on T_KONFIGAMBJENTE.IDKONFIGAMBJENTE=T_KUSHTEMPLATE.IDKONFIGAMBJENTE 
		JOIN T_KUSHTE on T_KUSHTE.IDKUSHT = T_KUSHTEMPLATE.IDKUSHT and T_KUSHTE.KODI = 'PM' 
WHERE	T_KONFIGAMBJENTE.IDNDERMARJE = @idndermarje
		AND T_KONFIGAMBJENTE.IDSTATUSDOK=1 
		AND T_KUSHTEMPLATE.vlera IN ( SELECT IDALTERNATIVEKUSHTI FROM T_ALTERNATIVAKUSHTI WHERE ALTERNATIVA='Po')
PRINT '@KONFIGAMB : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()

CREATE TABLE #idmax(idartikull int, idmag int, idrend int, PRIMARY KEY (idartikull, idmag, idrend))
INSERT INTO #idmax
SELECT DISTINCT m.IDARTIKULL, m.idmag, max(tt.idrenditjes) 
FROM T_TRUPIMAGAZINA tt 
	INNER JOIN #TempTrupiIns m ON  tt.IDARTIKULL=m.idartikull AND tt.IDMAG=m.idmag AND tt.DATA = convert(datetime, m.DATA, 103)
GROUP BY m.idArtikull, m.IDMAG
PRINT '#idmax : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()

DECLARE @DTDOK datetime= (SELECT TOP 1 convert(datetime, data, 103) FROM #TempTrupiIns)
CREATE TABLE #Progresivi (Rendi int, id numeric(18,0), idmag numeric(18,0), idartikull numeric (18,0), iddet numeric(18,0), sasiprog FLOAT, vleraprog FLOAT, sasiprogdet FLOAT, vleraprogdet FLOAT, PRIMARY KEY (idmag,idartikull,iddet))
;With CTE
As
(
	SELECT	RN= ROW_NUMBER() Over(Partition by tm.IDMAG, tm.IDARTIKULL, tm.IDDETAJIMI Order By tm.IDMAG, tm.IDARTIKULL, tm.IDDETAJIMI, tm.data desc, tm.IDRENDITJES,  tm.IDTRUPIMAGAZINA), 
			tm.IDRENDITJES, tm.IDTRUPIMAGAZINA, tm.IDMAG, tm.IDARTIKULL, tm.IDDETAJIMI,tm.SASIAPROGRESIVE, tm.VLEFTAPROGRESIVE, tm.SASIPROGRESIVEDETAJIMI, tm.VLEFTEPROGRESIVEDETAJIMI
	FROM	#TempTrupiIns m 
			INNER JOIN T_TRUPIMAGAZINA tm ON tm.IDARTIKULL =m.IDARTIKULL  AND  tm.IDMAG = m.IDMAG AND ISNULL(tm.IDDETAJIMI,-1) =ISNULL(m.IDDETAJIMI, -1)
			INNER JOIN T_KOKAMAGAZINA km ON km.IDKOKAMAGAZINA=tm.IDKOKAMAGAZINA 
			INNER JOIN #KONFIGAMB konfig on  km.IDKONFIGAMBJENTE=konfig.id 
			LEFT JOIN #idmax tt ON tt.idartikull = M.idartikull AND tt.IDMAG=m.idmag
	WHERE	tm.IDSTATUSDOK = 1 and tm.IDTRUPIMAGAZINA <> m.IDTRUPIMAGAZINA 
			AND tm.DATA = convert(datetime, @DTDOK, 103) and tm.IDRENDITJES <=TT.idrend	
)
INSERT INTO #Progresivi
Select 		IDRENDITJES, IDTRUPIMAGAZINA, IDMAG, IDARTIKULL, ISNULL(IDDETAJIMI,-1), SASIAPROGRESIVE, VLEFTAPROGRESIVE, SASIPROGRESIVEDETAJIMI, VLEFTEPROGRESIVEDETAJIMI
From		CTE
Where		RN = 1

;With CTE
As
(
SELECT  RN= ROW_NUMBER() Over(Partition by tm.IDMAG, tm.IDARTIKULL, tm.IDDETAJIMI Order By tm.IDMAG, tm.IDARTIKULL, tm.IDDETAJIMI, tm.data desc, tm.IDRENDITJES,  tm.IDTRUPIMAGAZINA), 
		tm.IDRENDITJES, tm.IDTRUPIMAGAZINA, tm.IDMAG, tm.IDARTIKULL, tm.IDDETAJIMI,tm.SASIAPROGRESIVE, tm.VLEFTAPROGRESIVE, tm.SASIPROGRESIVEDETAJIMI, tm.VLEFTEPROGRESIVEDETAJIMI
	FROM  (
			SELECT	DISTINCT eshte.IDMAG, eshte.IDARTIKULL, eshte.IDDETAJIMI  
			FROm	#TempTrupiIns eshte
					LEFT JOIN #Progresivi nukEshte ON eshte.IDMAG = nukEshte.idmag AND eshte.IDARTIKULL = nukEshte.IDARTIKULL AND ISNULL(eshte.IDDETAJIMI,-1) = nukEshte.iddet
			WHERE	nukEshte.IDARTIKULL IS NULL
		) m
		INNER JOIN T_TRUPIMAGAZINA tm ON tm.IDARTIKULL =m.IDARTIKULL AND  tm.IDMAG = m.IDMAG AND ISNULL(tm.IDDETAJIMI,-1) =ISNULL(m.IDDETAJIMI, -1)
		INNER JOIN T_KOKAMAGAZINA km on km.IDKOKAMAGAZINA=tm.IDKOKAMAGAZINA  
		INNER JOIN #KONFIGAMB konfig ON km.IDKONFIGAMBJENTE= konfig.id 		
	WHERE tm.IDSTATUSDOK = 1 AND tm.DATA < @DTDOK
)
INSERT INTO #Progresivi
Select 		IDRENDITJES, IDTRUPIMAGAZINA, IDMAG, IDARTIKULL, ISNULL(IDDETAJIMI,-1), SASIAPROGRESIVE, VLEFTAPROGRESIVE, SASIPROGRESIVEDETAJIMI, VLEFTEPROGRESIVEDETAJIMI
From		CTE
Where		RN = 1


UPDATE trupi
SET		trupi.SASIAPROGRESIVE = isnull(PROGRESIVE.sasiprog, 0) + trupi.SASIA * trupi.SHENJA * trupi.KOEFICENTI + isnull(PROG.SASIA,0),
		VLEFTAPROGRESIVE =	ISNULL((trupi.VLEFTA*trupi.SHENJA),0) + ISNULL(PROGRESIVE.vleraprog,0)+ ISNULL(PROG.VLERA,0),
		SASIPROGRESIVEDETAJIMI=	ISNULL((trupi.SASIA*trupi.SHENJA*trupi.KOEFICENTI),0)+ ISNULL(PROGRESIVEDET.sasiprogdet, 0)+ ISNULL(PROGRESIVEDETAJIMI.SASIA,0),
		VLEFTEPROGRESIVEDETAJIMI = ISNULL((trupi.VLEFTA*trupi.SHENJA),0) + ISNULL(PROGRESIVEDET.vleraprogdet, 0)+ ISNULL(PROGRESIVEDETAJIMI.VLERA,0)

from	T_TRUPIMAGAZINA trupi 
		inner join #TempTrupiIns te_rejat ON trupi.IDTRUPIMAGAZINA = te_rejat.IDTRUPIMAGAZINA		
		OUTER APPLY(
			SELECT	TOP 1 tm.sasiprog, TM.vleraprog
			FROM	#Progresivi AS tm 
			WHERE	te_rejat.idartikull=tm.idartikull AND tm.idmag=te_rejat.idmag 
			ORDER BY tm.idmag,tm.idartikull,tm.iddet, Rendi desc, id desc
		) PROGRESIVE
		OUTER APPLY(
			SELECT	TOP 1 tm.sasiprogdet, TM.vleraprogdet
			FROM	#Progresivi AS tm 
			WHERE  ISNULL(tm.IDDET,-1) = trupi.iddetajimi AND te_rejat.idartikull=tm.idartikull AND tm.idmag=te_rejat.idmag 
			ORDER BY tm.idmag,tm.idartikull,tm.iddet, Rendi desc, id desc
		) PROGRESIVEDET				
		OUTER APPLY(
			SELECT	sum(sasia*shenja*KOEFICENTI) as SASIA, sum (vlefta*shenja) as VLERA
			FROM	#TempTrupiIns tt 
			WHERE	tt.idartikull=te_rejat.idartikull AND tt.idmag=te_rejat.idmag AND tt.IDRENDITJES<te_rejat.idrenditjes
		) PROG
		OUTER APPLY(
			SELECT	sum (sasia*shenja*KOEFICENTI) as SASIA, sum((tt.VLEFTA*tt.shenja)) as VLERA
			FROM	#TempTrupiIns tt 
			where	tt.idartikull=te_rejat.idartikull AND tt.idmag=te_rejat.idmag AND tt.IDRENDITJES<te_rejat.idrenditjes AND tt.IDDETAJIMI=te_rejat.iddetajimi
		)PROGRESIVEDETAJIMI


PRINT 'trupi vlera progresive  : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()
	IF @newIdRenditje =1 
	BEGIN
		UPDATE trupi
		SET IDRENDITJES = ISNULL(RENDITJA.IDRENDITJES,0) + (case when @isDalje =1 then @koefDalje else @koefHyrje end) * te_rejat.IDRENDITJES
		FROM T_TRUPIMAGAZINA trupi 
			INNER JOIN #TempTrupiIns te_rejat ON trupi.IDTRUPIMAGAZINA = te_rejat.IDTRUPIMAGAZINA
			OUTER APPLY (select top(1) t.IDRENDITJES
						 from T_TRUPIMAGAZINA AS T 
							inner join T_KOKAMAGAZINA AS K on T.IDKOKAMAGAZINA=K.IDKOKAMAGAZINA 
						 where T.IDMAG = trupi.IDMAG and data = CONVERT(DATETIME, trupi.DATA, 103) AND K.IDSTATUSDOK<>2 
								and te_rejat.IDKOKAMAGAZINA != k.IDKOKAMAGAZINA
						order by T.IDRENDITJES desc
			) RENDITJA
		PRINT 'RENDITJA  : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()
	END

	
	SELECT * from #TempTrupiIns;
	PRINT '#TempTrupiIns  : ms(' + CAST(DATEDIFF (millisecond, @EXECTIME, GETDATE()) AS VARCHAR(200)) +')'; SET @EXECTIME = GETDATE()
	PRINT 'KOHA TOTAL: ms(' + CAST(DATEDIFF (millisecond, @TIMESTAMPFILLO, GETDATE()) AS VARCHAR(200)) +')'

END;
GO
