-- Rikthen indeksin para 10-nr-reference.sql (NRREFERENCE si kolone INCLUDE).
CREATE NONCLUSTERED INDEX T_KOKAFLETEKONTABEL_23072018
    ON dbo.T_KOKAFLETEKONTABEL (IDNDERVITI)
    INCLUDE (NRREFERENCEKOKAFLETEKONTABEL)
    WITH (DROP_EXISTING = ON);
GO
