-- 14 - Adresa e klientit ne procedurat e klient/furnitoreve
--
-- Pese procedura (merrKlientFurnitorSipasKodit, MerrSipasIdve, MerrSipasKodeve, KtheKlienteFurnitoreSipasAutorizimeveLike,
-- KtheSipasIdShitjeKoka) merrnin adresen e pare te klientit duke renditur (ROW_NUMBER) te gjithe tabelen
-- T_ADRESAKLIENTFURNITOR ne cdo thirrje (~12 500 rreshta, ~10 ms). Tani: TOP (1) per kete klient, kerkim ne indeksin
-- (IDKLIENTFURNITOR, IDTIPADRESE, ADRESA) qe ekziston. E njejta adrese (e para sipas llojit te adreses).
-- merrKlientFurnitorSipasKodit therritet per cdo klient ne importin e shitjeve/blerjeve dhe ne regjistrimin e dokumenteve.
-- Rikthimi: 14-rollback-adresa-klienti.sql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[prc_T_KLIENTFURNITOR_merrKlientFurnitorSipasKodit]
(
	@KODKLIENTFURNITOR T_PERSHKRIM,
	@IDNDERMARJE T_FOR_KEY	
)
AS
BEGIN

DECLARE @Err Int

SELECT kf.IDKLIENTFURNITOR, KODKLIENTFURNITOR, ll.NRLLOGARI, kf.IDLLOGARI, LLOJIKF, TITULLIKF, AKTIVITETIKF, EMERTIMIKF, EMERKERKRIMIKF, NIPTKF, QYTETIKF, SHTETIKF, TELKF, FAXKF, CELKF, 
		EMAILKF, WEBPAGEKF, IBANKF, LLOGARIBANKAREKF, AKTIVKF, IDLLOGZBRITJE, IDLLOGARIDYTESORE, IDKUSHTEPAGESE, IDMETODA, MATURIMIKF, IDKATZBRITJE, LIMITPARALAJMERUES, LIMITBLLOKUES, 
		IDKATEGORIKLIENTI, KUSHTEDERGIMI, MENYRATRASPORTIT, OFERTAAUTOMATIKE, VLERALIMITPOROSITUR, PRIORITETI, CMIMULET, kf.IDNIVELCMIMI, IDPERFAQESUESSHITJE, IDQENDERKOSTO, IDFUSHATA,
		ZBRITJEANALITIKE, ZBRITJETOTAL, kf.IDNDERMARJE, VITI, kf.IDPERDORUESI , kf.IDKONFIG, ll2.NRLLOGARI as NRLLOGARIZBRITJE, kz.KODKATEGORIZBRITJE, kz.ZBRITJA, nc.PERSHKRIMNIVELCMIMI, 
		kp.KODIKUSHTPAGESE, ash.KODIAGJENTSHITJE, nz.PERSHKRIMNIVELZBRITJE, q.QYTETIEMRI, kf.idstatusdok, kf.dtkrijimi, kf.dtmodifikimi, KF.LICENCA, KF.SWIFT, KF.EMRIBANKA, KF.ADRESABANKA,
		gr1.KODGRUPI AS Grupim1KF, gr2.KODGRUPI AS Grupim2KF, gr3.KODGRUPI AS Grupim3KF, kf.NRTVSH AS NrTVSH, o.KODI AS Objektiva, kf.IDOBJEKTIVAKOSTO IdObjektivaKosto, KF.IDKRIJUESI,
		T_PERDORUESI.PERDORUESEMRI as Krijuesi, IDNDERMARJEBIJ, LLOJPOROSIE, KUPON, kf.KOORDINATA.STAsText() AS Koordinata, IDPERFAQESUESSHITJE2,ash2.KODIAGJENTSHITJE KODIAGJENTSHITJE2,
		KLIENTSPECIFIK as KlientSpecifik,	FERMER ,AUTONGARKESE ,	SHITJEPATVSH ,ll3.NRLLOGARI as NRLLOGDYTESOR ,PERQINDJEAGJENTI,PERQINDJEAGJENTI2,PROSPEKT, EMAILPERPAJISJE,
		IDKLIENTFURNITORKRYESOR,kf.Shenime, DATELINDJAKF as DteDatelindjaKF, IDPERFAQESUESSHITJE3 AS IdPerfaqesuesShitje3,ash3.KODIAGJENTSHITJE AS KodPerfaqesuesShitje3,
		PERQINDJEAGJENTI3 AS PerqindjeAgjenti3, IDTVSH , Kf.EMERTIMFATURE  ,Kf.LLOGARITKOMISION , kf.KodIntegrimi, kf.KODIISKSH, T_ADRESAKLIENTFURNITOR.ADRESA,	kf.MEDOGANE AS MeDogane, kf.TIPIID AS TIPIID

FROM t_klientfurnitor kf 
	INNER JOIN T_LLOGARI ll on kf.IDLLOGARI = ll.IDLLOGARI
	LEFT OUTER JOIN T_LLOGARI ll2 on kf.IDLLOGZBRITJE = ll2.IDLLOGARI
	LEFT OUTER JOIN T_LLOGARI ll3 on kf.IDLLOGARIDYTESORE = ll3.IDLLOGARI
	LEFT OUTER JOIN T_KOKAKATEGORIZBRITJE kz on kf.IDKATZBRITJE = kz.IDKOKAKATEGORIZBRITJE
	LEFT OUTER JOIN T_NIVELCMIMI nc on kf.IDNIVELCMIMI = nc.IDNIVELCMIMI
	LEFT OUTER JOIN T_KUSHTPAGESEKOKA kp on kf.IDKUSHTEPAGESE = kp.IDKOKA
	LEFT OUTER JOIN T_AGJENTSHITJE ash on kf.IDPERFAQESUESSHITJE = ash.IDAGJENTSHITJE
	LEFT OUTER JOIN T_AGJENTSHITJE ash2 on kf.IDPERFAQESUESSHITJE2 = ash2.IDAGJENTSHITJE
	LEFT OUTER JOIN T_AGJENTSHITJE ash3 on kf.IDPERFAQESUESSHITJE3 = ash3.IDAGJENTSHITJE
	LEFT OUTER JOIN T_NIVELZBRITJE nz on kf.ZBRITJEANALITIKE =nz.IDNIVELZBRITJE
	LEFT OUTER JOIN T_QYTETI q on kf.QYTETIKF = q.IDQYTETI
	LEFT OUTER JOIN dbo.T_GRUPEKF gr1 ON kf.GRUPIM1KF = gr1.IDGRUPI
	LEFT OUTER JOIN dbo.T_GRUPEKF gr2 ON kf.GRUPIM2KF = gr2.IDGRUPI
	LEFT OUTER JOIN dbo.T_GRUPEKF gr3 ON kf.GRUPIM3KF = gr3.IDGRUPI
	LEFT OUTER JOIN dbo.T_OBJEKTIVAKOSTO o ON kf.idobjektivakosto=o.ID
	LEFT OUTER JOIN dbo.T_PERDORUESI ON KF.IDKRIJUESI=T_PERDORUESI.IDPERDORUES
	OUTER APPLY (
				-- adresa e pare e klientit (si ROW_NUMBER() ... rn = 1, por kerkim ne indeks vetem per kete klient)
				SELECT TOP (1) a.IDKLIENTFURNITOR, a.ADRESA, CAST(1 AS bigint) AS rn
				FROM T_ADRESAKLIENTFURNITOR a
				WHERE a.IDKLIENTFURNITOR = kf.IDKLIENTFURNITOR
				ORDER BY a.IDTIPADRESE, a.ADRESA
			) AS T_ADRESAKLIENTFURNITOR		
WHERE KODKLIENTFURNITOR = @KODKLIENTFURNITOR and kf.IDNDERMARJE = @IDNDERMARJE AND kf.idstatusdok<>2 and prospekt <>1
                            
	Set @Err = @@Error

	RETURN @Err
	
END
GO
ALTER PROCEDURE [dbo].[prc_T_KLIENTFURNITOR_MerrSipasIdve]
(
	@IDS VARCHAR(MAX)
)
AS
BEGIN
	DECLARE @Err INT

	DECLARE @IDTE AS TABLE( IDKLIENTFURNITOR INT );
	INSERT INTO @IDTE(IDKLIENTFURNITOR)
	SELECT	*
	FROM	DBO.SPLIT_STRING( @IDS, ',' )

	SELECT	DISTINCT KF.IDKLIENTFURNITOR
			,KODKLIENTFURNITOR
			,ll.NRLLOGARI
			,kf.IDLLOGARI
			,LLOJIKF
			,TITULLIKF
			,AKTIVITETIKF
			,EMERTIMIKF
			,EMERKERKRIMIKF
			,NIPTKF
			,QYTETIKF
			,SHTETIKF
			,TELKF
			,FAXKF
			,CELKF
			,EMAILKF
			,WEBPAGEKF
			,IBANKF
			,LLOGARIBANKAREKF
			,AKTIVKF
			,IDLLOGZBRITJE
			,IDLLOGARIDYTESORE
			,IDKUSHTEPAGESE
			,IDMETODA
			,MATURIMIKF
			,IDKATZBRITJE
			,LIMITPARALAJMERUES
			,LIMITBLLOKUES
			,IDKATEGORIKLIENTI
			,KUSHTEDERGIMI
			,MENYRATRASPORTIT
			,OFERTAAUTOMATIKE
			,VLERALIMITPOROSITUR
			,PRIORITETI
			,CMIMULET
			,kf.IDNIVELCMIMI
			,IDPERFAQESUESSHITJE
			,IDQENDERKOSTO
			,IDFUSHATA
			,ZBRITJEANALITIKE
			,ZBRITJETOTAL
			,kf.IDNDERMARJE
			,VITI
			,kf.IDPERDORUESI
			,kf.IDKONFIG
			,ll2.NRLLOGARI as NRLLOGARIZBRITJE
			,kz.KODKATEGORIZBRITJE
			,kz.ZBRITJA
			,nc.PERSHKRIMNIVELCMIMI
			,kp.KODIKUSHTPAGESE
			,ash.KODIAGJENTSHITJE
			,nz.PERSHKRIMNIVELZBRITJE
			,q.QYTETIEMRI
			,KF.IDSTATUSDOK
			,KF.DTKRIJIMI
			,KF.DTMODIFIKIMI
			,KF.LICENCA
			,KF.SWIFT
			,KF.EMRIBANKA
			,KF.ADRESABANKA
			,gr1.KODGRUPI AS Grupim1KF
			,gr2.KODGRUPI AS Grupim2KF
			,gr3.KODGRUPI AS Grupim3KF
			,kf.NRTVSH AS NrTVSH
			,o.KODI AS Objektiva
			,kf.IDOBJEKTIVAKOSTO IdObjektivaKosto
			,KF.IDKRIJUESI
			,T_PERDORUESI.PERDORUESEMRI as Krijuesi
			,IDNDERMARJEBIJ
			,LLOJPOROSIE
			,KUPON
			,kf.KOORDINATA.STAsText() AS Koordinata
			,ash2.KODIAGJENTSHITJE KODIAGJENTSHITJE2
			,IDPERFAQESUESSHITJE2
			,KLIENTSPECIFIK
			,FERMER AS Fermer
			,AUTONGARKESE as AutoNgarkese
			,SHITJEPATVSH as ShitjePaTvsh
			,ll3.NRLLOGARI as NRLLOGDYTESOR
			,kf.PERQINDJEAGJENTI as PerqindjeAgjenti
			,kf.PERQINDJEAGJENTI2 as PerqindjeAgjenti2
			,PROSPEKT as Prospekt
			,EMAILPERPAJISJE AS EmailPerPajisje
			,IDKLIENTFURNITORKRYESOR as IdKlientFurnitorKryesor
			,kf.Shenime as Shenime
			,DATELINDJAKF as DteDatelindjaKF
			,IDPERFAQESUESSHITJE3 AS IdPerfaqesuesShitje3
			,ash3.KODIAGJENTSHITJE AS KodPerfaqesuesShitje3
			,PERQINDJEAGJENTI3 AS PerqindjeAgjenti3
			,IDTVSH 
			,Kf.EMERTIMFATURE 
			,kf.LLOGARITKOMISION
			,kf.KodIntegrimi
			,kf.KODIISKSH  as KodiISKSH,
			T_ADRESAKLIENTFURNITOR.ADRESA,
			MEDOGANE,
			TIPIID
	FROM	T_KLIENTFURNITOR kf 
			INNER JOIN	@IDTE AS IDS
				ON IDS.IDKLIENTFURNITOR = KF.IDKLIENTFURNITOR
			LEFT JOIN T_LLOGARI ll 
				on kf.IDLLOGARI = ll.IDLLOGARI 
			LEFT JOIN T_LLOGARI ll2 
				on kf.IDLLOGZBRITJE = ll2.IDLLOGARI
			LEFT JOIN T_LLOGARI ll3 
				on kf.IDLLOGARIDYTESORE = ll3.IDLLOGARI
			LEFT JOIN T_KOKAKATEGORIZBRITJE kz 
				on kf.IDKATZBRITJE = kz.IDKOKAKATEGORIZBRITJE
			LEFT JOIN T_NIVELCMIMI nc 
				on kf.IDNIVELCMIMI = nc.IDNIVELCMIMI
			LEFT JOIN T_KUSHTPAGESEKOKA kp 
				on kf.IDKUSHTEPAGESE = kp.IDKOKA
			LEFT JOIN T_AGJENTSHITJE ash 
				on kf.IDPERFAQESUESSHITJE = ash.IDAGJENTSHITJE
			LEFT JOIN T_AGJENTSHITJE ash2 
				on kf.IDPERFAQESUESSHITJE2 = ash2.IDAGJENTSHITJE
			LEFT JOIN T_AGJENTSHITJE ash3 
				on kf.IDPERFAQESUESSHITJE3 = ash3.IDAGJENTSHITJE
			LEFT JOIN T_NIVELZBRITJE nz 
				on kf.ZBRITJEANALITIKE =nz.IDNIVELZBRITJE
			LEFT JOIN T_QYTETI q 
				on kf.QYTETIKF = q.IDQYTETI
			LEFT JOIN dbo.T_GRUPEKF gr1 
				ON kf.GRUPIM1KF = gr1.IDGRUPI
			LEFT JOIN dbo.T_GRUPEKF gr2 
				ON kf.GRUPIM2KF = gr2.IDGRUPI
			LEFT JOIN dbo.T_GRUPEKF gr3 
				ON kf.GRUPIM3KF = gr3.IDGRUPI
			LEFT JOIN dbo.T_OBJEKTIVAKOSTO o 
				ON kf.idobjektivakosto=o.ID
			LEFT JOIN dbo.T_PERDORUESI 
				ON KF.IDKRIJUESI=T_PERDORUESI.IDPERDORUES		
			OUTER APPLY (
				-- adresa e pare e klientit (si ROW_NUMBER() ... rn = 1, por kerkim ne indeks vetem per kete klient)
				SELECT TOP (1) a.IDKLIENTFURNITOR, a.ADRESA, CAST(1 AS bigint) AS rn
				FROM T_ADRESAKLIENTFURNITOR a
				WHERE a.IDKLIENTFURNITOR = kf.IDKLIENTFURNITOR
				ORDER BY a.IDTIPADRESE, a.ADRESA
			) AS T_ADRESAKLIENTFURNITOR

	SET @Err = @@Error
    RETURN @Err
END
GO
ALTER PROCEDURE [dbo].[prc_T_KLIENTFURNITOR_MerrSipasKodeve]
(
	@KODET VARCHAR(MAX),
	@IDNDERMARRJE INT
)
AS
BEGIN
	DECLARE @Err INT

	SELECT	KF.IDKLIENTFURNITOR
			,KODKLIENTFURNITOR
			,ll.NRLLOGARI
			,kf.IDLLOGARI
			,LLOJIKF
			,TITULLIKF
			,AKTIVITETIKF
			,EMERTIMIKF
			,EMERKERKRIMIKF
			,NIPTKF
			,QYTETIKF
			,SHTETIKF
			,TELKF
			,FAXKF
			,CELKF
			,EMAILKF
			,WEBPAGEKF
			,IBANKF
			,LLOGARIBANKAREKF
			,AKTIVKF
			,IDLLOGZBRITJE
			,IDLLOGARIDYTESORE
			,IDKUSHTEPAGESE
			,IDMETODA
			,MATURIMIKF
			,IDKATZBRITJE
			,LIMITPARALAJMERUES
			,LIMITBLLOKUES
			,IDKATEGORIKLIENTI
			,KUSHTEDERGIMI
			,MENYRATRASPORTIT
			,OFERTAAUTOMATIKE
			,VLERALIMITPOROSITUR
			,PRIORITETI
			,CMIMULET
			,kf.IDNIVELCMIMI
			,IDPERFAQESUESSHITJE
			,IDQENDERKOSTO
			,IDFUSHATA
			,ZBRITJEANALITIKE
			,ZBRITJETOTAL
			,kf.IDNDERMARJE
			,VITI
			,kf.IDPERDORUESI
			,kf.IDKONFIG
			,ll2.NRLLOGARI as NRLLOGARIZBRITJE
			,kz.KODKATEGORIZBRITJE
			,kz.ZBRITJA
			,nc.PERSHKRIMNIVELCMIMI
			,kp.KODIKUSHTPAGESE
			,ash.KODIAGJENTSHITJE
			,nz.PERSHKRIMNIVELZBRITJE
			,q.QYTETIEMRI
			,KF.IDSTATUSDOK
			,KF.DTKRIJIMI
			,KF.DTMODIFIKIMI
			,KF.LICENCA
			,KF.SWIFT
			,KF.EMRIBANKA
			,KF.ADRESABANKA
			,gr1.KODGRUPI AS Grupim1KF
			,gr2.KODGRUPI AS Grupim2KF
			,gr3.KODGRUPI AS Grupim3KF
			,kf.NRTVSH AS NrTVSH
			,o.KODI AS Objektiva
			,kf.IDOBJEKTIVAKOSTO IdObjektivaKosto
			,KF.IDKRIJUESI
			,T_PERDORUESI.PERDORUESEMRI as Krijuesi
			,IDNDERMARJEBIJ
			,LLOJPOROSIE
			,KUPON
			,kf.KOORDINATA.STAsText() AS Koordinata
			,ash2.KODIAGJENTSHITJE KODIAGJENTSHITJE2
			,IDPERFAQESUESSHITJE2
			,KLIENTSPECIFIK
			,FERMER AS Fermer
			,AUTONGARKESE as AutoNgarkese
			,SHITJEPATVSH as ShitjePaTvsh
			,ll3.NRLLOGARI as NRLLOGDYTESOR
			,kf.PERQINDJEAGJENTI as PerqindjeAgjenti
			,kf.PERQINDJEAGJENTI2 as PerqindjeAgjenti2
			,PROSPEKT as Prospekt
			,EMAILPERPAJISJE AS EmailPerPajisje
			,IDKLIENTFURNITORKRYESOR as IdKlientFurnitorKryesor
			,kf.Shenime as Shenime
			,DATELINDJAKF as DteDatelindjaKF
			,IDPERFAQESUESSHITJE3 AS IdPerfaqesuesShitje3
			,ash3.KODIAGJENTSHITJE AS KodPerfaqesuesShitje3
			,PERQINDJEAGJENTI3 AS PerqindjeAgjenti3
			,IDTVSH 
			,Kf.EMERTIMFATURE 
			,kf.LLOGARITKOMISION
			,kf.KodIntegrimi
			,kf.KODIISKSH  as KodiISKSH,
			T_ADRESAKLIENTFURNITOR.ADRESA,
			kf.MEDOGANE AS MeDogane,
			kf.TIPIID AS TIPIID

	FROM	T_KLIENTFURNITOR kf 
	INNER JOIN dbo.SPLIT_STRING(@KODET,',') kodet on kodet.splitdata = kf.KODKLIENTFURNITOR
			LEFT JOIN T_LLOGARI ll 
				on kf.IDLLOGARI = ll.IDLLOGARI 
			LEFT JOIN T_LLOGARI ll2 
				on kf.IDLLOGZBRITJE = ll2.IDLLOGARI
			LEFT JOIN T_LLOGARI ll3 
				on kf.IDLLOGARIDYTESORE = ll3.IDLLOGARI
			LEFT JOIN T_KOKAKATEGORIZBRITJE kz 
				on kf.IDKATZBRITJE = kz.IDKOKAKATEGORIZBRITJE
			LEFT JOIN T_NIVELCMIMI nc 
				on kf.IDNIVELCMIMI = nc.IDNIVELCMIMI
			LEFT JOIN T_KUSHTPAGESEKOKA kp 
				on kf.IDKUSHTEPAGESE = kp.IDKOKA
			LEFT JOIN T_AGJENTSHITJE ash 
				on kf.IDPERFAQESUESSHITJE = ash.IDAGJENTSHITJE
			LEFT JOIN T_AGJENTSHITJE ash2 
				on kf.IDPERFAQESUESSHITJE2 = ash2.IDAGJENTSHITJE
			LEFT JOIN T_AGJENTSHITJE ash3 
				on kf.IDPERFAQESUESSHITJE3 = ash3.IDAGJENTSHITJE
			LEFT JOIN T_NIVELZBRITJE nz 
				on kf.ZBRITJEANALITIKE =nz.IDNIVELZBRITJE
			LEFT JOIN T_QYTETI q 
				on kf.QYTETIKF = q.IDQYTETI
			LEFT JOIN dbo.T_GRUPEKF gr1 
				ON kf.GRUPIM1KF = gr1.IDGRUPI
			LEFT JOIN dbo.T_GRUPEKF gr2 
				ON kf.GRUPIM2KF = gr2.IDGRUPI
			LEFT JOIN dbo.T_GRUPEKF gr3 
				ON kf.GRUPIM3KF = gr3.IDGRUPI
			LEFT JOIN dbo.T_OBJEKTIVAKOSTO o 
				ON kf.idobjektivakosto=o.ID
			LEFT JOIN dbo.T_PERDORUESI 
				ON KF.IDKRIJUESI=T_PERDORUESI.IDPERDORUES	
			OUTER APPLY (
				-- adresa e pare e klientit (si ROW_NUMBER() ... rn = 1, por kerkim ne indeks vetem per kete klient)
				SELECT TOP (1) a.IDKLIENTFURNITOR, a.ADRESA, CAST(1 AS bigint) AS rn
				FROM T_ADRESAKLIENTFURNITOR a
				WHERE a.IDKLIENTFURNITOR = kf.IDKLIENTFURNITOR
				ORDER BY a.IDTIPADRESE, a.ADRESA
			) AS T_ADRESAKLIENTFURNITOR		
	WHERE	kf.IDNDERMARJE = @IDNDERMARRJE and kf.IDSTATUSDOK = 1 and kf.AKTIVKF=1

	SET @Err = @@Error
    RETURN @Err
END
GO
ALTER PROCEDURE [dbo].[prc_T_KLIENTFURNITOR_KtheKlienteFurnitoreSipasAutorizimeveLike]
(
	@IDNDERMARJE varchar(20),
	@IDPERDORUES varchar(20),
	@KODKLIENTFURNITOR T_pershkrim,
	@LLOJI VARCHAR(1),
	@IDKLIENTFURNITORKRYESOR varchar(20)
)
AS
BEGIN


	DECLARE @Err Int
	
	DECLARE @QUERY VARCHAR(MAX) = '
	SELECT top 10 kf.IDKLIENTFURNITOR, KODKLIENTFURNITOR,ll.NRLLOGARI, kf.IDLLOGARI, LLOJIKF, TITULLIKF, AKTIVITETIKF, EMERTIMIKF, EMERKERKRIMIKF, NIPTKF, QYTETIKF, SHTETIKF, TELKF, FAXKF, CELKF,
			EMAILKF, WEBPAGEKF, IBANKF, LLOGARIBANKAREKF, AKTIVKF, IDLLOGZBRITJE, IDLLOGARIDYTESORE, IDKUSHTEPAGESE, IDMETODA, MATURIMIKF, IDKATZBRITJE, LIMITPARALAJMERUES, LIMITBLLOKUES,
			IDKATEGORIKLIENTI, KUSHTEDERGIMI, MENYRATRASPORTIT, OFERTAAUTOMATIKE, VLERALIMITPOROSITUR, PRIORITETI, CMIMULET, kf.IDNIVELCMIMI, IDPERFAQESUESSHITJE, IDQENDERKOSTO, IDFUSHATA,
			ZBRITJEANALITIKE, ZBRITJETOTAL, kf.IDNDERMARJE, VITI, kf.IDPERDORUESI, kf.IDKONFIG,
			ll2.NRLLOGARI as NRLLOGARIZBRITJE,kz.KODKATEGORIZBRITJE,kz.ZBRITJA,nc.PERSHKRIMNIVELCMIMI ,kp.KODIKUSHTPAGESE,ash.KODIAGJENTSHITJE, nz.PERSHKRIMNIVELZBRITJE, q.QYTETIEMRI,
			kf.idstatusdok, kf.dtkrijimi, kf.dtmodifikimi, KF.LICENCA, KF.SWIFT, KF.EMRIBANKA, KF.ADRESABANKA, gr1.KODGRUPI AS Grupim1KF, gr2.KODGRUPI AS Grupim2KF, gr3.KODGRUPI AS Grupim3KF,
			kf.NRTVSH AS NrTVSH, o.KODI AS Objektiva, kf.IDOBJEKTIVAKOSTO IdObjektivaKosto, KF.IDKRIJUESI, T_PERDORUESI.PERDORUESEMRI as Krijuesi, IDNDERMARJEBIJ, LLOJPOROSIE, KUPON, 
			ll3.NRLLOGARI AS NrLlogDytesor, kf.KOORDINATA.STAsText() AS Koordinata , ash2.KODIAGJENTSHITJE KODIAGJENTSHITJE2, IDPERFAQESUESSHITJE2,KLIENTSPECIFIK,	FERMER AS Fermer , 
			AUTONGARKESE as AutoNgarkese ,	SHITJEPATVSH as ShitjePaTvsh,PERQINDJEAGJENTI as PerqindjeAgjenti, PERQINDJEAGJENTI2 as PerqindjeAgjenti2,PROSPEKT as Prospekt, EMAILPERPAJISJE AS EmailPerPajisje,
			IDKLIENTFURNITORKRYESOR as IdKlientFurnitorKryesor,kf.Shenime as Shenime, DATELINDJAKF AS DteDatelindjaKF, IDPERFAQESUESSHITJE3 AS IdPerfaqesuesShitje3,
			ash3.KODIAGJENTSHITJE AS KodPerfaqesuesShitje3, PERQINDJEAGJENTI3 AS PerqindjeAgjenti3 ,IDTVSH  , Kf.EMERTIMFATURE , kf.LLOGARITKOMISION , kf.KodIntegrimi,
			kf.KODIISKSH AS KodiISKSH, ADRESA, MEDOGANE,TIPIID
	FROM	T_KLIENTFURNITOR kf 
			INNER JOIN T_LLOGARI ll on kf.IDLLOGARI = ll.IDLLOGARI
			LEFT OUTER JOIN T_LLOGARI ll2 on kf.IDLLOGZBRITJE = ll2.IDLLOGARI
			LEFT OUTER JOIN T_LLOGARI ll3 on kf.IDLLOGARIDYTESORE = ll3.IDLLOGARI
			LEFT OUTER JOIN T_KOKAKATEGORIZBRITJE kz on kf.IDKATZBRITJE = kz.IDKOKAKATEGORIZBRITJE
			LEFT OUTER JOIN T_NIVELCMIMI nc on kf.IDNIVELCMIMI = nc.IDNIVELCMIMI
			LEFT OUTER JOIN T_KUSHTPAGESEKOKA kp on kf.IDKUSHTEPAGESE = kp.IDKOKA
			LEFT OUTER JOIN T_AGJENTSHITJE ash on kf.IDPERFAQESUESSHITJE = ash.IDAGJENTSHITJE
			LEFT OUTER JOIN T_AGJENTSHITJE ash2 on kf.IDPERFAQESUESSHITJE2 = ash2.IDAGJENTSHITJE
			LEFT OUTER JOIN T_AGJENTSHITJE ash3 on kf.IDPERFAQESUESSHITJE3 = ash3.IDAGJENTSHITJE
			LEFT OUTER JOIN T_NIVELZBRITJE nz on kf.ZBRITJEANALITIKE =nz.IDNIVELZBRITJE
			LEFT OUTER JOIN T_QYTETI q on kf.QYTETIKF = q.IDQYTETI
			LEFT OUTER JOIN dbo.T_GRUPEKF gr1 ON kf.GRUPIM1KF = gr1.IDGRUPI
			LEFT OUTER JOIN dbo.T_GRUPEKF gr2 ON kf.GRUPIM2KF = gr2.IDGRUPI
			LEFT OUTER JOIN dbo.T_GRUPEKF gr3 ON kf.GRUPIM3KF = gr3.IDGRUPI
			LEFT OUTER JOIN dbo.T_OBJEKTIVAKOSTO o ON kf.idobjektivakosto=o.ID
			LEFT OUTER JOIN dbo.T_PERDORUESI ON KF.IDKRIJUESI=T_PERDORUESI.IDPERDORUES  
			OUTER APPLY (
				-- adresa e pare e klientit (si ROW_NUMBER() ... rn = 1, por kerkim ne indeks vetem per kete klient)
				SELECT TOP (1) a.IDKLIENTFURNITOR, a.ADRESA, CAST(1 AS bigint) AS rn
				FROM T_ADRESAKLIENTFURNITOR a
				WHERE a.IDKLIENTFURNITOR = kf.IDKLIENTFURNITOR
				ORDER BY a.IDTIPADRESE, a.ADRESA
			) AS T_ADRESAKLIENTFURNITOR			
			OUTER APPLY (SELECT * FROM dbo.eshteIAutorizuar(kf.IDKLIENTFURNITOR,''KlientFurnitor'', '+@IDPERDORUES+')) AUTORIZIM
	WHERE	kf.IDNDERMARJE = '+@IDNDERMARJE +'
			AND kf.AKTIVKF=''true''
			AND kf.idstatusdok <> 2 
			AND (kf.KODKLIENTFURNITOR LIKE ''%'+@KODKLIENTFURNITOR+'%'' OR kf.EMERTIMIKF LIKE ''%'+@KODKLIENTFURNITOR+'%'') 
			AND AUTORIZIM.AUTORIZUAR = 1	'

			IF(@LLOJI <> '2')
			BEGIN
				SET @QUERY = @QUERY + ' AND kf.LLOJIKF = ' + @LLOJI
			END
			IF(@IDKLIENTFURNITORKRYESOR <> '0')
			BEGIN
				SET @QUERY = @QUERY + ' AND isnull(kf.IDKLIENTFURNITORKRYESOR,0) = ' + @IDKLIENTFURNITORKRYESOR
			END
			
	PRINT (@QUERY)
	EXEC (@QUERY)
	Set @Err = @@Error
	RETURN @Err	

END

select * from T_KLIENTFURNITOR
GO
ALTER PROCEDURE [dbo].[prc_T_KLIENTFURNITOR_KtheSipasIdShitjeKoka]
(
	@IDSHITJEKOKA VARCHAR(MAX)
)
AS
BEGIN
	DECLARE @Err INT

	SELECT	KF.IDKLIENTFURNITOR
			,KODKLIENTFURNITOR
			,ll.NRLLOGARI
			,kf.IDLLOGARI
			,LLOJIKF
			,TITULLIKF
			,AKTIVITETIKF
			,EMERTIMIKF
			,EMERKERKRIMIKF
			,NIPTKF
			,QYTETIKF
			,SHTETIKF
			,TELKF
			,FAXKF
			,CELKF
			,EMAILKF
			,WEBPAGEKF
			,IBANKF
			,LLOGARIBANKAREKF
			,AKTIVKF
			,IDLLOGZBRITJE
			,IDLLOGARIDYTESORE
			,IDKUSHTEPAGESE
			,IDMETODA
			,MATURIMIKF
			,IDKATZBRITJE
			,LIMITPARALAJMERUES
			,LIMITBLLOKUES
			,IDKATEGORIKLIENTI
			,KUSHTEDERGIMI
			,MENYRATRASPORTIT
			,OFERTAAUTOMATIKE
			,VLERALIMITPOROSITUR
			,PRIORITETI
			,CMIMULET
			,kf.IDNIVELCMIMI
			,IDPERFAQESUESSHITJE
			,IDQENDERKOSTO
			,IDFUSHATA
			,ZBRITJEANALITIKE
			,ZBRITJETOTAL
			,kf.IDNDERMARJE
			,VITI
			,kf.IDPERDORUESI
			,kf.IDKONFIG
			,ll2.NRLLOGARI as NRLLOGARIZBRITJE
			,kz.KODKATEGORIZBRITJE
			,kz.ZBRITJA
			,nc.PERSHKRIMNIVELCMIMI
			,kp.KODIKUSHTPAGESE
			,ash.KODIAGJENTSHITJE
			,nz.PERSHKRIMNIVELZBRITJE
			,q.QYTETIEMRI
			,KF.IDSTATUSDOK
			,KF.DTKRIJIMI
			,KF.DTMODIFIKIMI
			,KF.LICENCA
			,KF.SWIFT
			,KF.EMRIBANKA
			,KF.ADRESABANKA
			,gr1.KODGRUPI AS Grupim1KF
			,gr2.KODGRUPI AS Grupim2KF
			,gr3.KODGRUPI AS Grupim3KF
			,kf.NRTVSH AS NrTVSH
			,o.KODI AS Objektiva
			,kf.IDOBJEKTIVAKOSTO IdObjektivaKosto
			,KF.IDKRIJUESI
			,T_PERDORUESI.PERDORUESEMRI as Krijuesi
			,IDNDERMARJEBIJ
			,LLOJPOROSIE
			,KUPON
			,kf.KOORDINATA.STAsText() AS Koordinata
			,ash2.KODIAGJENTSHITJE KODIAGJENTSHITJE2
			,IDPERFAQESUESSHITJE2
			,KLIENTSPECIFIK
			,FERMER AS Fermer
			,AUTONGARKESE as AutoNgarkese
			,SHITJEPATVSH as ShitjePaTvsh
			,ll3.NRLLOGARI as NRLLOGDYTESOR
			,kf.PERQINDJEAGJENTI as PerqindjeAgjenti
			,kf.PERQINDJEAGJENTI2 as PerqindjeAgjenti2
			,PROSPEKT as Prospekt
			,EMAILPERPAJISJE AS EmailPerPajisje
			,IDKLIENTFURNITORKRYESOR as IdKlientFurnitorKryesor
			,kf.Shenime as Shenime
			,DATELINDJAKF as DteDatelindjaKF
			,IDPERFAQESUESSHITJE3 AS IdPerfaqesuesShitje3
			,ash3.KODIAGJENTSHITJE AS KodPerfaqesuesShitje3
			,PERQINDJEAGJENTI3 AS PerqindjeAgjenti3
			,IDTVSH 
			,Kf.EMERTIMFATURE 
			,kf.LLOGARITKOMISION
			,kf.KodIntegrimi
			,kf.KODIISKSH  as KodiISKSH,
			ADRESA,
			kf.MEDOGANE AS MeDogane,
			kf.TIPIID AS TIPIID
	FROM	T_KLIENTFURNITOR kf 
			INNER JOIN	T_KOKASHITJE_KLIENTVARTES
				ON	T_KOKASHITJE_KLIENTVARTES.IDKLIENTFURNITOR = kf.IDKLIENTFURNITOR
					AND T_KOKASHITJE_KLIENTVARTES.IDSHITJEKOKA = @IDSHITJEKOKA
			LEFT JOIN T_LLOGARI ll 
				on kf.IDLLOGARI = ll.IDLLOGARI 
			LEFT JOIN T_LLOGARI ll2 
				on kf.IDLLOGZBRITJE = ll2.IDLLOGARI
			LEFT JOIN T_LLOGARI ll3 
				on kf.IDLLOGARIDYTESORE = ll3.IDLLOGARI
			LEFT JOIN T_KOKAKATEGORIZBRITJE kz 
				on kf.IDKATZBRITJE = kz.IDKOKAKATEGORIZBRITJE
			LEFT JOIN T_NIVELCMIMI nc 
				on kf.IDNIVELCMIMI = nc.IDNIVELCMIMI
			LEFT JOIN T_KUSHTPAGESEKOKA kp 
				on kf.IDKUSHTEPAGESE = kp.IDKOKA
			LEFT JOIN T_AGJENTSHITJE ash 
				on kf.IDPERFAQESUESSHITJE = ash.IDAGJENTSHITJE
			LEFT JOIN T_AGJENTSHITJE ash2 
				on kf.IDPERFAQESUESSHITJE2 = ash2.IDAGJENTSHITJE
			LEFT JOIN T_AGJENTSHITJE ash3 
				on kf.IDPERFAQESUESSHITJE3 = ash3.IDAGJENTSHITJE
			LEFT JOIN T_NIVELZBRITJE nz 
				on kf.ZBRITJEANALITIKE =nz.IDNIVELZBRITJE
			LEFT JOIN T_QYTETI q 
				on kf.QYTETIKF = q.IDQYTETI
			LEFT JOIN dbo.T_GRUPEKF gr1 
				ON kf.GRUPIM1KF = gr1.IDGRUPI
			LEFT JOIN dbo.T_GRUPEKF gr2 
				ON kf.GRUPIM2KF = gr2.IDGRUPI
			LEFT JOIN dbo.T_GRUPEKF gr3 
				ON kf.GRUPIM3KF = gr3.IDGRUPI
			LEFT JOIN dbo.T_OBJEKTIVAKOSTO o 
				ON kf.idobjektivakosto=o.ID
			LEFT JOIN dbo.T_PERDORUESI 
				ON KF.IDKRIJUESI=T_PERDORUESI.IDPERDORUES			
				OUTER APPLY (
				-- adresa e pare e klientit (si ROW_NUMBER() ... rn = 1, por kerkim ne indeks vetem per kete klient)
				SELECT TOP (1) a.IDKLIENTFURNITOR, a.ADRESA, CAST(1 AS bigint) AS rn
				FROM T_ADRESAKLIENTFURNITOR a
				WHERE a.IDKLIENTFURNITOR = kf.IDKLIENTFURNITOR
				ORDER BY a.IDTIPADRESE, a.ADRESA
			) AS T_ADRESAKLIENTFURNITOR		
	SET @Err = @@Error
    RETURN @Err
END
GO
