//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.5.47.2/Kasa/KasaWebService.asmx")]
        public string DbCore_KasaService_KasaWebService {
            get {
                return ((string)(this["DbCore_KasaService_KasaWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebInf")]
        public string DbCore_EmriDatabaze_Import {
            get {
                return ((string)(this["DbCore_EmriDatabaze_Import"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_TEMP_KOKA_IMPORT_FLETEKONTABEL")]
        public string DbCore_EmriTabeles_ImportKokaFleteKontabel {
            get {
                return ((string)(this["DbCore_EmriTabeles_ImportKokaFleteKontabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_TEMP_TRUPI_IMPORT_FLETEKONTABEL")]
        public string DbCore_EmriTabeles_ImportTrupiFleteKontabel {
            get {
                return ((string)(this["DbCore_EmriTabeles_ImportTrupiFleteKontabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_TEMP_IMPORTPOLICA")]
        public string DbCore_EmriTabeles_ImportAlbSigFleteKontabel {
            get {
                return ((string)(this["DbCore_EmriTabeles_ImportAlbSigFleteKontabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DbCoreKontrollFkPresjeDhjetore {
            get {
                return ((int)(this["DbCoreKontrollFkPresjeDhjetore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://195.233.190.109/axis2/services/VFALSendSMSGateWay.VFALSendSMSGateWayHttpSo" +
            "ap11Endpoint/")]
        public string DbCore_VodSendSMS_Service_VFALSendSMSGateWay {
            get {
                return ((string)(this["DbCore_VodSendSMS_Service_VFALSendSMSGateWay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://osb-preprod-vfal.internal.vodafone.com:80/VFALSelfCareOperationsOSBProxy/p" +
            "roxy/VFALSelfCareOperationsProxy")]
        public string DbCore_PromocioneProxy1_VFALSelfCareOperations {
            get {
                return ((string)(this["DbCore_PromocioneProxy1_VFALSelfCareOperations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://osb-preprod-vfal.internal.vodafone.com:80/VFALBRMServicesOSBProject/proxy/" +
            "VFALBRMServicesOSBProxy")]
        public string DbCore_BRMAdapterServices_BRMAdapterServicesSoap12BindingQSService {
            get {
                return ((string)(this["DbCore_BRMAdapterServices_BRMAdapterServicesSoap12BindingQSService"]));
            }
        }
    }
}
