IF OBJECT_ID('prc_T_TIPIEINVOICE_merrPershkrimEINVOICE') IS NOT NULL
	DROP PROCEDURE prc_T_TIPIEINVOICE_merrPershkrimEINVOICE
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[prc_T_TIPIEINVOICE_merrPershkrimEINVOICE]
(
@KODI T_KOD_VAR
)
AS
    BEGIN
        Select PERSHKRIMI from T_TIPIEINVOICE WHERE KODI= @KODI;
    END;