
DECLARE @IDKOMPONENTE NUMERIC(18, 0) = (SELECT IDKOMPON FROM T_KOMPONENTE WHERE KOMPONEMRI = 'Shto_KartaKlienti.aspx')
DECLARE @IDKONTROLLI NUMERIC(18, 0)

IF NOT EXISTS(SELECT * FROM T_KONTROLLE WHERE IDKOMPONENTE=@IDKOMPONENTE AND KODKONTROLL='lblGjendjepikesh')
BEGIN
		
	INSERT INTO T_KONTROLLE(IDGRUP, IDKOMPONENTE, KODKONTROLL, PERSHKRIMKONTROLL, TIPI, EMERIMPORTI, SHFAQIMPORTI, PERMOBILE)
	VALUES(NULL, @IDKOMPONENTE, 'lblGjendjepikesh', 'Gjendje pikesh', 0, '', 0, 0)

	SET @IDKONTROLLI = @@IDENTITY
	
	INSERT INTO T_ATRIBUTETRUPI(IDKONTROLL, IDKONFIGAMBJENTE, VLEREDEFAULT_sq, VISIBLE, ENABLED1, IDKONFIGLUPA, IDENTIFIKUES, RRESHTI, KOLONA, 
	DETYRUESHME, IDNRAUTOMATIK, VLEREDEFAULT_en, SHFAQMOBILE, RENDITJAMOBILE, UNIKE, VLEREDEFAULT_fr)
	SELECT @IDKONTROLLI, IDKONFIGAMBJENTE, 'Gjendje pikesh:', 0,1 , NULL, 3, 7, 3, 0, NULL, '', 0, 0, 0, ''
	FROM T_KONFIGAMBJENTE
	WHERE IDKATDOK IN (1, 2)

END

IF NOT EXISTS(SELECT * FROM T_KONTROLLE WHERE IDKOMPONENTE = @IDKOMPONENTE AND KODKONTROLL = 'txtGjendjepikesh')
BEGIN	

	INSERT INTO T_KONTROLLE(IDGRUP, IDKOMPONENTE, KODKONTROLL, PERSHKRIMKONTROLL, TIPI, EMERIMPORTI, SHFAQIMPORTI, PERMOBILE)
	VALUES(NULL, @IDKOMPONENTE, 'txtGjendjepikesh', 'Caktimi i gjendjeve te pikeve', 2, 'Gjendje pikesh', 0, 0)

	SET @IDKONTROLLI = @@IDENTITY

	INSERT INTO T_ATRIBUTETRUPI(IDKONTROLL, IDKONFIGAMBJENTE, VLEREDEFAULT_sq, VISIBLE, ENABLED1, IDKONFIGLUPA, IDENTIFIKUES, RRESHTI, KOLONA, 
	DETYRUESHME, IDNRAUTOMATIK, VLEREDEFAULT_en, SHFAQMOBILE, RENDITJAMOBILE, UNIKE, VLEREDEFAULT_fr)
	SELECT @IDKONTROLLI, IDKONFIGAMBJENTE, 'Gjendje pikesh', 0, 0, NULL, 3, 37, 4, 0, NULL, '', 0, 0, 0, ''
	FROM T_KONFIGAMBJENTE
	WHERE IDKATDOK IN (1, 2)

END