DECLARE @IDKOMPONENTE NUMERIC(18, 0) = (SELECT IDKOMPON FROM T_KOMPONENTE WHERE KOMPONEMRI = 'Shto_KartaKlienti.aspx')
DECLARE @IDKONTROLLI NUMERIC(18, 0) = (SELECT IDKONTROLL FROM T_KONTROLLE WHERE IDKOMPONENTE = @IDKOMPONENTE AND KODKONTROLL = 'txtGjendjepikesh')
DECLARE @IDKATDOK NUMERIC(18, 0) = (select IDKATDOK from T_KATEGORINIVELDOK where PERSHKRIMI_sq = 'Karta Klienti')
IF NOT EXISTS(SELECT * FROM T_TRUPIFORMATIMPORTI WHERE IDKONTROLL=@IDKONTROLLI AND EMERIMPORTI = 'Gjendje pikesh')
BEGIN
	INSERT INTO T_TRUPIFORMATIMPORTI(IDKOKA, IDKONTROLL, EMERIMPORTI, DETYRUESHME, SHFAQ, RENDI, VISIBLE,TIPI,DETYRUESHMEDEFAULT,FUSHETYPE)
    SELECT IDKOKA, @IDKONTROLLI, 'Gjendje pikesh', 0, 1, 8, 1,1,0,'int' from T_KOKAFORMATIMPORTI where IDKATEGORI = @IDKATDOK
END
