IF EXISTS 
	(SELECT 1 FROM sys.objects WHERE [NAME] = 'prc_T_TABELATEMPORARE_del' AND [TYPE] = 'P')
	DROP PROCEDURE prc_T_TABELATEMPORARE_del
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[prc_T_TABELATEMPORARE_del]
(
	@TABELAKOKA varchar(max),
	@TABELATRUPI varchar(max),
	@TABELAKOKAHISTORIK varchar(max),
	@TABELATRUPIHISTORIK varchar(max)
)
AS
BEGIN
DECLARE @Err Int
DECLARE @sql varchar(MAX) = @TABELAKOKA + @TABELATRUPI + @TABELAKOKAHISTORIK + @TABELATRUPIHISTORIK
	EXEC(@TABELAKOKA)
	EXEC(@TABELATRUPI)
	EXEC(@TABELAKOKAHISTORIK)
	EXEC(@TABELATRUPIHISTORIK)
	Set @Err = @@Error

	RETURN @Err
	
END
