DECLARE @IDKOMPONENTE NUMERIC(18, 0) = (SELECT IDKOMPON FROM T_KOMPONENTE WHERE KOMPONEMRI = 'Shto_KlientFurnitor.aspx?kf=klient')
DECLARE @IDKONTROLLI NUMERIC(18, 0) = (SELECT IDKONTROLL FROM T_KONTROLLE WHERE IDKOMPONENTE = @IDKOMPONENTE AND KODKONTROLL = 'cmbTipiId')
DECLARE @IDKATDOK NUMERIC(18, 0) = (select IDKATDOK from T_KATEGORINIVELDOK where PERSHKRIMI_sq = 'Klient/Furnitor')

IF NOT EXISTS(SELECT * FROM T_TRUPIFORMATIMPORTI WHERE IDKONTROLL=@IDKONTROLLI AND EMERIMPORTI = 'Tipi Id')
BEGIN
	INSERT INTO T_TRUPIFORMATIMPORTI(IDKOKA, IDKONTROLL, EMERIMPORTI, DETYRUESHME, SHFAQ, RENDI, VISIBLE,TIPI,DETYRUESHMEDEFAULT,FUSHETYPE)
	SELECT IDKOKA, @IDKONTROLLI, 'Tipi Id', 0, 0, 53, 0,1,0,'varchar(20)' from T_KOKAFORMATIMPORTI where IDKATEGORI = @IDKATDOK
END
