
IF NOT EXISTS(
  SELECT *
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE 
    TABLE_NAME = 'T_SERVER_CONNECTIONSTRINGS'
    AND COLUMN_NAME = 'INTEGRIM')

BEGIN

ALTER TABLE T_SERVER_CONNECTIONSTRINGS
ADD [INTEGRIM] [bit] DEFAULT ((0))

END

