DECLARE @IDKOMPONENTE NUMERIC(18, 0) = (SELECT IDKOMPON FROM T_KOMPONENTE WHERE KOMPONEMRI = 'Shto_Artikull.aspx?llojiart=afatshkurter')
DECLARE @IDKONTROLLI NUMERIC(18, 0) = (SELECT IDKONTROLL FROM T_KONTROLLE WHERE IDKOMPONENTE = @IDKOMPONENTE AND KODKONTROLL = 'cbIRimbursueshem')
DECLARE @IDKATDOK NUMERIC(18, 0) = (select IDKATDOK from T_KATEGORINIVELDOK where PERSHKRIMI_sq = 'Artikuj afatshkurter/afatgjate')

IF NOT EXISTS(SELECT * FROM T_TRUPIFORMATIMPORTI WHERE IDKONTROLL=@IDKONTROLLI AND EMERIMPORTI = 'I rimbursueshem')
BEGIN
	INSERT INTO T_TRUPIFORMATIMPORTI(IDKOKA, IDKONTROLL, EMERIMPORTI, DETYRUESHME, SHFAQ, RENDI, VISIBLE,TIPI,DETYRUESHMEDEFAULT,FUSHETYPE)
	SELECT IDKOKA, @IDKONTROLLI, 'I rimbursueshem', 0, 0, 70, 1,1,0,'bit' from T_KOKAFORMATIMPORTI where IDKATEGORI = @IDKATDOK
END