DECLARE @IDKOMPONENTE NUMERIC(18, 0) = (SELECT IDKOMPON FROM T_KOMPONENTE WHERE KOMPONEMRI = 'Shto_Artikull.aspx?llojiart=afatshkurter')
DECLARE @IDKONTROLLI NUMERIC(18, 0) = (SELECT IDKONTROLL FROM T_KONTROLLE WHERE IDKOMPONENTE = @IDKOMPONENTE AND KODKONTROLL = 'txtKodiIBarit')

IF EXISTS(SELECT * FROM T_TRUPIFORMATIMPORTI WHERE IDKONTROLL=@IDKONTROLLI AND EMERIMPORTI = 'Kodi i barit')
BEGIN
	UPDATE T_TRUPIFORMATIMPORTI
	SET VISIBLE = 0
	where IDKONTROLL=@IDKONTROLLI AND EMERIMPORTI = 'Kodi i barit'
END
