
DECLARE @IDKOMPONENTE NUMERIC(18, 0) = (SELECT IDKOMPON FROM T_KOMPONENTE WHERE KOMPONEMRI = 'Shto_RegjistrimDokumentash.aspx?shitje_blerje=shitje')
DECLARE @IDKONTROLLI NUMERIC(18, 0)

IF NOT EXISTS(SELECT * FROM T_KONTROLLE WHERE IDKOMPONENTE=@IDKOMPONENTE AND KODKONTROLL='lblDocumentEinvoice')
BEGIN
		
	INSERT INTO T_KONTROLLE(IDGRUP, IDKOMPONENTE, KODKONTROLL, PERSHKRIMKONTROLL, TIPI, EMERIMPORTI, SHFAQIMPORTI, PERMOBILE)
	VALUES(NULL, @IDKOMPONENTE, 'lblDocumentEinvoice', 'Ngarko Dokumentin', 0, '', 0, 0)

	SET @IDKONTROLLI = @@IDENTITY
	
	INSERT INTO T_ATRIBUTETRUPI(IDKONTROLL, IDKONFIGAMBJENTE, VLEREDEFAULT_sq, VISIBLE, ENABLED1, IDKONFIGLUPA, IDENTIFIKUES, RRESHTI, KOLONA, 
	DETYRUESHME, IDNRAUTOMATIK, VLEREDEFAULT_en, SHFAQMOBILE, RENDITJAMOBILE, UNIKE, VLEREDEFAULT_fr)
	SELECT @IDKONTROLLI, IDKONFIGAMBJENTE, 'Ngarko Dokumentin:', 0, 1, NULL, 3, 33, 8, 0, NULL, '', 0, 0, 0, ''
	FROM T_KONFIGAMBJENTE
	WHERE IDKATDOK IN (1,2)

END

IF NOT EXISTS(SELECT * FROM T_KONTROLLE WHERE IDKOMPONENTE=@IDKOMPONENTE AND KODKONTROLL='UcDocumentEinvoice')
BEGIN
		
	INSERT INTO T_KONTROLLE(IDGRUP, IDKOMPONENTE, KODKONTROLL, PERSHKRIMKONTROLL, TIPI, EMERIMPORTI, SHFAQIMPORTI, PERMOBILE)
	VALUES(NULL, @IDKOMPONENTE, 'UcDocumentEinvoice', 'Zgjedhja e documentit e-invoice', 13, '', 0, 0)

	SET @IDKONTROLLI = @@IDENTITY
	
	INSERT INTO T_ATRIBUTETRUPI(IDKONTROLL, IDKONFIGAMBJENTE, VLEREDEFAULT_sq, VISIBLE, ENABLED1, IDKONFIGLUPA, IDENTIFIKUES, RRESHTI, KOLONA, 
	DETYRUESHME, IDNRAUTOMATIK, VLEREDEFAULT_en, SHFAQMOBILE, RENDITJAMOBILE, UNIKE, VLEREDEFAULT_fr)
	SELECT @IDKONTROLLI, IDKONFIGAMBJENTE, '', 0, 1, NULL, 3, 33, 8, 0, NULL, '', 0, 0, 0, ''
	FROM T_KONFIGAMBJENTE
	WHERE IDKATDOK IN (1,2)

END

IF NOT EXISTS(SELECT * FROM T_KONTROLLE WHERE IDKOMPONENTE=@IDKOMPONENTE AND KODKONTROLL='upload')
BEGIN
		
	INSERT INTO T_KONTROLLE(IDGRUP, IDKOMPONENTE, KODKONTROLL, PERSHKRIMKONTROLL, TIPI, EMERIMPORTI, SHFAQIMPORTI, PERMOBILE)
	VALUES(NULL, @IDKOMPONENTE, 'upload', 'Ngarko', 6, '', 0, 0)

	SET @IDKONTROLLI = @@IDENTITY
	
	INSERT INTO T_ATRIBUTETRUPI(IDKONTROLL, IDKONFIGAMBJENTE, VLEREDEFAULT_sq, VISIBLE, ENABLED1, IDKONFIGLUPA, IDENTIFIKUES, RRESHTI, KOLONA, 
	DETYRUESHME, IDNRAUTOMATIK, VLEREDEFAULT_en, SHFAQMOBILE, RENDITJAMOBILE, UNIKE, VLEREDEFAULT_fr)
	SELECT @IDKONTROLLI, IDKONFIGAMBJENTE, '', 0, 1, NULL, 3, 33, 8, 0, NULL, '', 0, 0, 0, ''
	FROM T_KONFIGAMBJENTE
	WHERE IDKATDOK IN (1,2)

END
