IF OBJECT_ID('prc_T_OPERATORE_sel') IS NOT NULL
	DROP PROCEDURE prc_T_OPERATORE_sel
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[prc_T_OPERATORE_sel]
AS
	BEGIN
		DECLARE @Err INT
		SELECT KODI + ' ' + '(' + EMRI + ' ' + MBIEMRI + ')' FROM T_OPERATORE
	
	 SET @Err = @@Error
	 RETURN @Err
	END
