
IF EXISTS(
  SELECT *
  FROM INFORMATION_SCHEMA.TABLES
  WHERE 
    TABLE_NAME = 'T_TRUPIFORMATIMPORTI'
   )

BEGIN
  update T_TRUPIFORMATIMPORTI
  set FUSHETYPE = 'VARCHAR(100)'
  where EMERIMPORTI = 'Nr Dokumenti' AND FUSHETYPE = 'varchar(20)'
END