IF EXISTS(SELECT * FROM T_GRIDATRUPI WHERE GRIDATRUPIKODI = 'EIC')
BEGIN
	update T_GRIDATRUPI 
	set VISIBLECOSTUMIZE = 1
	where GRIDATRUPIKODI = 'EIC'
END

IF EXISTS(SELECT * FROM T_GRIDATRUPI WHERE GRIDATRUPIKODI = 'NIVF')
BEGIN
	update T_GRIDATRUPI 
	set VISIBLECOSTUMIZE = 1
	where GRIDATRUPIKODI = 'NIVF'
END

IF EXISTS(SELECT * FROM T_GRIDATRUPI WHERE GRIDATRUPIKODI = 'IdOperator')
BEGIN
	update T_GRIDATRUPI 
	set VISIBLECOSTUMIZE = 1
	where GRIDATRUPIKODI = 'IdOperator'
END

IF EXISTS(SELECT * FROM T_GRIDATRUPI WHERE GRIDATRUPIKODI = 'IIC')
BEGIN
	update T_GRIDATRUPI 
	set VISIBLECOSTUMIZE = 1
	where GRIDATRUPIKODI = 'IIC'
END


IF EXISTS(SELECT * FROM T_GRIDATRUPI WHERE GRIDATRUPIKODI = 'Fiskalizuar')
BEGIN
	update T_GRIDATRUPI 
	set VISIBLECOSTUMIZE = 1
	where GRIDATRUPIKODI = 'Fiskalizuar'
END

IF EXISTS(SELECT * FROM T_GRIDATRUPI WHERE GRIDATRUPIKODI = 'EInvoice')
BEGIN
	update T_GRIDATRUPI 
	set VISIBLECOSTUMIZE = 1
	where GRIDATRUPIKODI = 'EInvoice'
END