IF OBJECT_ID('prc_T_TRUPISHITJE_selAllSipasKoka') IS NOT NULL
	DROP PROCEDURE prc_T_TRUPISHITJE_selAllSipasKoka
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[prc_T_TRUPISHITJE_selAllSipasKoka]
(
@IDSHITJEKOKA T_AUTO_NUM
)
AS
BEGIN

DECLARE @SASI INT= (SELECT TOP (1) IDTRUPIKTHIMI FROM T_TRUPISHITJE WHERE	T_TRUPISHITJE.IDSHITJEKOKA = @IDSHITJEKOKA)

	--marrim vleren e kushtit ndiko ne konvertim per dokumentin qe duam te kthejme
DECLARE @Alt varchar(100) =	(
									SELECT	ta.ALTERNATIVA 
									FROM	dbo.T_ALTERNATIVAKUSHTI ta 
											INNER JOIN dbo.T_KUSHTE tk 
												ON tk.IDKUSHT = ta.IDKUSHTI 
											INNER JOIN dbo.T_KUSHTEMPLATE tk2 
												ON	tk2.IDKUSHT = tk.IDKUSHT 
													AND tk2.VLERA = ta.IDALTERNATIVEKUSHTI 
											INNER JOIN T_KOKASHITJE 
												ON TK2.IDKONFIGAMBJENTE = T_KOKASHITJE.IDKONFIGAMBJENTE
									WHERE	tk.KODI='NK' 
											AND t_kokashitje.IDSHITJEKOKA = @IDSHITJEKOKA
							);

WITH CTE_SHITJE AS ( SELECT	*, IDHISTORIK = 0, IDKOKAHISTORIK = 0, LIDHUR = 0 
					 FROM	dbo.T_TRUPISHITJE  WHERE IDSHITJEKOKA = @IDSHITJEKOKA
					 UNION ALL  
					 SELECT	* 
					 FROM	T_TRUPISHITJEHISTORIK WHERE LIDHUR = 0 AND IDSHITJEKOKA = @IDSHITJEKOKA 
),
 CTE_KONVERTIMI AS (
		SELECT	SUM (ISNULL(CASE 
								WHEN	t.IDNJESIA = a1.NJESI1ARTIKULLI 
								THEN	t.SASIA 
								ELSE	t.SASIA * a1.KOEFICENTARTIKULLI 
							END ,0)) AS SASIA ,SUM(t.SASIA) AS SASIA2 
				,t.idtrupikonvertimi
		FROM	T_TRUPISHITJE t 
					INNER JOIN dbo.T_KOKASHITJE k  ON k.IDSHITJEKOKA=t.IDSHITJEKOKA  
					INNER JOIN CTE_SHITJE S ON  S.IDSHITJETRUPI = T.IDTRUPIKONVERTIMI
					LEFT OUTER JOIN t_artikulli a1 ON t.IDKODI=a1.IDARTIKULLI AND t.IDLLOJVEPRIMI=1 
		WHERE	k.IDSTATUSDOK<>2  
		GROUP BY T.IDTRUPIKONVERTIMI					 
),
 CTE_KONVERTIMIFSH AS (SELECT	SUM(ISNULL(	CASE WHEN	t.IDNJESIA = a1.NJESI1ARTIKULLI 
												 THEN	t.SASIA 
												 ELSE	t.SASIA * a1.KOEFICENTARTIKULLI 
											END ,0)) SASIA 	,t.idtrupikonvertimFSH
						FROM	T_TRUPIMAGAZINA T 
							INNER JOIN T_KOKAMAGAZINA K		ON K.IDKOKAMAGAZINA = T.IDKOKAMAGAZINA
							INNER JOIN CTE_SHITJE S			ON S.IDTRUPIKTHIMI = T.IDTRUPIKONVERTIMFSH 
							LEFT OUTER JOIN t_artikulli a1 	ON t.IDARTIKULL=a1.IDARTIKULLI AND t.IDLLOJVEPRIMI=1 
						WHERE	t.IDTRUPIKONVERTIMUD is null and k.IDSTATUSDOK<>2  
						GROUP BY idtrupikonvertimFSH	 
),
 CTE_KTHIMET AS (	
	    SELECT	SUM(T.SASIA + S.SASIA) SASIA , T.IDTRUPIKTHIMI 
		FROM	T_TRUPISHITJE T
			INNER JOIN	T_KOKASHITJE K ON	K.IDSHITJEKOKA = T.IDSHITJEKOKA 
			INNER JOIN  CTE_SHITJE S ON S.IDSHITJETRUPI  = T.IDTRUPIKTHIMI
		WHERE	T.IDLLOJVEPRIMI = 1 AND S.IDLLOJVEPRIMI = 1
		GROUP BY T.IDTRUPIKTHIMI
)


SELECT	IDSHITJETRUPI,IDSHITJEKOKA,IDLLOJVEPRIMI ,KODI ,PERSHKRIMI,IDDETAJIMART,IDNJESIA,SASIA,CMIMI,ZBRITJE,VLEFTAPATVSH,TVSH,VLEFTAMETVSH
			,IDMAGAZINA ,IDDETAJIMART2 ,IDKODI ,GJERESI	,GJATESI ,SASIPERMASE ,SHENIME ,DTFILLIMI ,DTMBARIMI ,IDTRUPIKONVERTIMI ,SASIREZ ,sasiambetur
			,IDTRUPIREZERVIMI ,IDTRUPITRANSFERIMI ,IDTRUPIKTHIMI,IDTRUPIKONVERTIMBLERJE ,IDLLOGSHPENZIMI ,NRLLOGARI AS NRLLOGSHPENZIMI ,SHENIME2
			,LLOJZBRITJE ,ZBRITJEVLERE ,a.IDKATEGORISHPENZIMI ,IDBARKODI ,IDTRUPITRANSFERIMNGA ,a.VleraKomision ,a.LLOGARITKOMISION 
			FROM	(
				    SELECT	t_trupishitje.*,
						ISNULL(	CASE WHEN	idllojveprimi = 1 
									 THEN	
										 CASE WHEN @SASI is null
										 then 
											(SELECT (SELECT SUM(-SASIA) FROM T_TRUPISHITJE t 
																				INNER JOIN dbo.T_KOKASHITJE k ON k.IDSHITJEKOKA=t.IDSHITJEKOKA
																				LEFT OUTER JOIN t_artikulli a1 ON t.IDKODI=a1.IDARTIKULLI AND t.IDLLOJVEPRIMI=1  where t.IDSHITJETRUPI = [T_TRUPISHITJE].IDSHITJETRUPI GROUP BY IDSHITJETRUPI)
																				- (SELECT SUM(ISNULL(CASE WHEN t.IDNJESIA=a1.NJESI1ARTIKULLI THEN t.SASIA ELSE t.SASIA*a1.KOEFICENTARTIKULLI END ,0)) 
																			FROM T_TRUPISHITJE t 
																				INNER JOIN dbo.T_KOKASHITJE k ON k.IDSHITJEKOKA=t.IDSHITJEKOKA
																				LEFT OUTER JOIN t_artikulli a1 ON t.IDKODI=a1.IDARTIKULLI AND t.IDLLOJVEPRIMI=1 
																			WHERE t.IDTRUPIKTHIMI = [T_TRUPISHITJE].IDSHITJETRUPI and k.IDSTATUSDOK<>2 
																			GROUP BY IDTRUPIKTHIMI))
										 else
											(SELECT (SELECT SUM(-SASIA) FROM T_TRUPISHITJE t 
																				INNER JOIN dbo.T_KOKASHITJE k ON k.IDSHITJEKOKA=t.IDSHITJEKOKA
																				LEFT OUTER JOIN t_artikulli a1 ON t.IDKODI=a1.IDARTIKULLI AND t.IDLLOJVEPRIMI=1  where t.IDTRUPIKTHIMI = [T_TRUPISHITJE].IDTRUPIKTHIMI GROUP BY IDTRUPIKTHIMI)
																				- (SELECT SUM(ISNULL(CASE WHEN t.IDNJESIA=a1.NJESI1ARTIKULLI THEN t.SASIA ELSE t.SASIA*a1.KOEFICENTARTIKULLI END ,0)) 
																			FROM T_TRUPISHITJE t 
																				INNER JOIN dbo.T_KOKASHITJE k ON k.IDSHITJEKOKA=t.IDSHITJEKOKA
																				LEFT OUTER JOIN t_artikulli a1 ON t.IDKODI=a1.IDARTIKULLI AND t.IDLLOJVEPRIMI=1
																			WHERE t.IDSHITJETRUPI = [T_TRUPISHITJE].IDTRUPIKTHIMI and k.IDSTATUSDOK<>2 
																			GROUP BY IDSHITJETRUPI))
																				
										 END
									 ELSE	T_TRUPISHITJE.SASIA - KONVERTIMI.SASIA2   
								 END,  T_TRUPISHITJE.SASIA
								)AS sasiambetur , NRLLOGARI
					FROM	CTE_SHITJE AS	T_TRUPISHITJE
						LEFT OUTER JOIN dbo.T_ARTIKULLI						ON T_TRUPISHITJE.IDKODI=IDARTIKULLI AND IDLLOJVEPRIMI=1
						LEFT OUTER JOIN dbo.T_LLOGARI						ON T_TRUPISHITJE.IDLLOGSHPENZIMI = T_LLOGARI.IDLLOGARI
						LEFT OUTER JOIN	CTE_KONVERTIMI		KONVERTIMI		ON KONVERTIMI.IDTRUPIKONVERTIMI = T_TRUPISHITJE.IDSHITJETRUPI
						LEFT OUTER JOIN	CTE_KONVERTIMIFSH	KONVERTIMIFSH	ON	KONVERTIMIFSH.IDTRUPIKONVERTIMFSH = T_TRUPISHITJE.IDTRUPIKTHIMI  --gjejme sasine e konvertuar ne dokument magazine te dokumentit kryesor
						LEFT JOIN	CTE_KTHIMET				KTHIMET			ON	KTHIMET.IDTRUPIKTHIMI = T_TRUPISHITJE.IDTRUPIKTHIMI	
				WHERE	T_TRUPISHITJE.IDSHITJEKOKA = @IDSHITJEKOKA)
				AS a 
	order by IDSHITJETRUPI

 

	RETURN @@Error
END