insert into T_PARAM(SPPARAMETEREMRI, SPPARAMETERPERSHK, SPCOLDBEMERLOGJIK,IDGRUPKONTROLL)
select 'filterDtDok', 'Date dokumenti', 'T_FATURAEINVOICE.DueDateTime',1
where NOT EXISTS(select * from T_PARAM where SPPARAMETEREMRI = 'filterDtDok' AND SPCOLDBEMERLOGJIK = 'T_FATURAEINVOICE.DueDateTime')
