DECLARE @IDPARAMETRIDTDOK T_FOR_KEY = (SELECT IDPARAMETRI FROM T_PARAM WHERE SPPARAMETEREMRI = 'filterDtDok' AND SPCOLDBEMERLOGJIK = 'T_FATURAEINVOICE.DueDateTime')
DECLARE @IDPARAMETRIEIC T_FOR_KEY = (SELECT IDPARAMETRI FROM T_PARAM WHERE SPPARAMETEREMRI = 'filterEIC' AND SPCOLDBEMERLOGJIK = 'T_FATURAEINVOICE.EIC')
DECLARE @IDPARAMETRISTATUSEINVOICE T_FOR_KEY = (SELECT IDPARAMETRI FROM T_PARAM WHERE SPPARAMETEREMRI = 'filterStatusEinvoice' AND SPCOLDBEMERLOGJIK = 'T_FATURAEINVOICE.Status')
DECLARE @IDSP T_FOR_KEY = (SELECT IDSP FROM T_SP WHERE SPEMRI = 'PRC_RAP_SHITJEPERMBLEDHESEINVOICE')

if NOT EXISTS(SELECT * FROM T_PARAMXSP where IDPARAMETRI = @IDPARAMETRIDTDOK AND IDSP = @IDSP)
BEGIN
	INSERT INTO T_PARAMXSP(IDSP,IDPARAMETRI)
	VALUES (@IDSP,@IDPARAMETRIDTDOK)
END
if NOT EXISTS(SELECT * FROM T_PARAMXSP where IDPARAMETRI = @IDPARAMETRIEIC AND IDSP = @IDSP)
BEGIN
	INSERT INTO T_PARAMXSP(IDSP,IDPARAMETRI)
	VALUES (@IDSP,@IDPARAMETRIEIC)
END
if NOT EXISTS(SELECT * FROM T_PARAMXSP where IDPARAMETRI = @IDPARAMETRISTATUSEINVOICE AND IDSP = @IDSP)
BEGIN
	INSERT INTO T_PARAMXSP(IDSP,IDPARAMETRI)
	VALUES (@IDSP,@IDPARAMETRISTATUSEINVOICE)
END