IF OBJECT_ID('prc_T_OPERATORE_sel') IS NOT NULL
	DROP PROCEDURE prc_T_OPERATORE_sel
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[prc_T_OPERATORE_sel]
(
  @IDNDERMARRJE T_FOR_KEY
)
AS
	BEGIN
		DECLARE @Err INT
		SELECT KODI FROM T_OPERATORE where IDSTATUSDOK=1 AND IDNDERMARRJE = @IDNDERMARRJE
	
	 SET @Err = @@Error
	 RETURN @Err
	END
