IF OBJECT_ID('prc_T_TIPIEINVOICE_selKodTipiEinvoice') IS NOT NULL
	DROP PROCEDURE prc_T_TIPIEINVOICE_selKodTipiEinvoice
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[prc_T_TIPIEINVOICE_selKodTipiEinvoice]
AS
	BEGIN
		DECLARE @Err INT
		SELECT KODI FROM T_TIPIEINVOICE
	
	 SET @Err = @@Error
	 RETURN @Err
	END
