IF OBJECT_ID('prc_T_PROCESI_selKodProcesi') IS NOT NULL
	DROP PROCEDURE prc_T_PROCESI_selKodProcesi
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[prc_T_PROCESI_selKodProcesi]
AS
	BEGIN
		DECLARE @Err INT
		SELECT KODI FROM T_PROCESI
	
	 SET @Err = @@Error
	 RETURN @Err
	END
