DECLARE @IDKOMPON INT = (SELECT IDKOMPON FROM T_KOMPONENTE where KOMPONEMRI = 'Shto_KlientFurnitor.aspx?kf=klient')
DECLARE @IDKONTROLL INT = (SELECT IDKONTROLL FROM T_KONTROLLE WHERE KODKONTROLL = 'cmbTipiId' AND IDKOMPONENTE = @IDKOMPON)
IF EXISTS(SELECT * FROM T_KONTROLLE WHERE KODKONTROLL = 'cmbTipiId' AND IDKOMPONENTE = @IDKOMPON)
BEGIN
	UPDATE T_KONTROLLE set SHFAQIMPORTI = 1 where IDKONTROLL = @IDKONTROLL
	update T_TRUPIFORMATIMPORTI set FUSHEKOKEAPOTRUPI = 1 
	where IDKONTROLL = @IDKONTROLL
END