IF OBJECT_ID('prc_Integrim_lexoKlientPasDatesSeFundit') IS NOT NULL
	DROP PROCEDURE prc_Integrim_lexoKlientPasDatesSeFundit
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[prc_Integrim_lexoKlientPasDatesSeFundit](
	@NRSEL AS VARCHAR(MAX),
	@NRCHUNK AS VARCHAR(MAX),
	@DTFUNDITLEXUAR VARCHAR(MAX),
	@NDERMARRJEKOD T_KOD_VAR,
	@PERDORUES T_KOD_VAR
)
AS
BEGIN
  --GJENERUAR NGA IMB SERVER API v2.1.0 GJATE UPGRADE
DECLARE @SHPREHJE AS VARCHAR(8000)
DECLARE @SHPREHJE1 AS VARCHAR(8000)
DECLARE @SHPREHJE2 AS VARCHAR(8000)
DECLARE @SHPREHJE3 AS VARCHAR(8000)
DECLARE @SHPREHJE4 AS VARCHAR(8000)
DECLARE @SHPREHJE5 AS VARCHAR(8000)
DECLARE @SHPREHJE6 AS VARCHAR(8000)
DECLARE @SHPREHJE7 AS VARCHAR(8000)
DECLARE @AUTORIZIM AS VARCHAR(8000)
DECLARE @JOAUTORIZIM AS VARCHAR(8000)
DECLARE @DATEMINIMALE datetime
SET @DATEMINIMALE = 0
IF(@PERDORUES <> '')	
begin
-- deklarojme kushtet e autorizimeve
	SET @AUTORIZIM = ' 
			AND (T_KLIENTFURNITOR.IDKLIENTFURNITOR in (select IDLIDHESE  from  T_LIDHJEAUTORIZIM  where T_LIDHJEAUTORIZIM.IDSTATUSDOK=1 
			AND IDAUTORIZIMEKOKA in (select IDAUTORIZIMKOKA  from T_AUTORIZIMTRUPI  where IDPERDORUESI=(SELECT IDPERDORUES FROM T_PERDORUESI WHERE IDSTATUSDOK=1 AND PERDORUESUSERNAME=''' + @PERDORUES + ''')) 
			AND IDLLOJI in (select idllojbuxheti from T_LLOJBUXHETI  where KODLLOJBUXHETI=''KlientFurnitor''))
			OR T_KLIENTFURNITOR.IDKLIENTFURNITOR not in (select idlidhese from T_LIDHJEAUTORIZIM where IDLLOJI in (select idllojbuxheti from T_LLOJBUXHETI  where KODLLOJBUXHETI=''KlientFurnitor'') 
			AND T_LIDHJEAUTORIZIM.IDSTATUSDOK=1)) AND T_NDERMARJE.IDSTATUSDOK = 1  '

	SET @JOAUTORIZIM ='
		    AND (T_KLIENTFURNITOR.IDKLIENTFURNITOR in (
		    select IDLIDHESE  from  T_LIDHJEAUTORIZIM  
			JOIN T_AUTORIZIMKOKA ON T_AUTORIZIMKOKA.IDAUTORIZIMEKOKA=T_LIDHJEAUTORIZIM.IDAUTORIZIMEKOKA
			JOIN T_AUTORIZIMTRUPI ON T_AUTORIZIMTRUPI.IDAUTORIZIMKOKA=T_AUTORIZIMKOKA.IDAUTORIZIMEKOKA
					INNER JOIN T_NDERMARJE ON T_AUTORIZIMKOKA.IDNDERMARJE = T_NDERMARJE.IDNDERMARJE
			WHERE T_AUTORIZIMTRUPI.IDPERDORUESI in (SELECT IDPERDORUES FROM T_PERDORUESI WHERE IDSTATUSDOK=1 AND PERDORUESUSERNAME=''' + @PERDORUES + ''') AND  T_NDERMARJE.NDERMARJEKODI=''' + @NDERMARRJEKOD + '''
			AND T_LIDHJEAUTORIZIM.IDSTATUSDOK=2 AND IDLLOJI in (select idllojbuxheti from T_LLOJBUXHETI  where KODLLOJBUXHETI=''KlientFurnitor''))

			OR (T_KLIENTFURNITOR.IDKLIENTFURNITOR  in (select IDLIDHESE  from  T_LIDHJEAUTORIZIM  
			JOIN T_AUTORIZIMKOKA ON T_AUTORIZIMKOKA.IDAUTORIZIMEKOKA=T_LIDHJEAUTORIZIM.IDAUTORIZIMEKOKA
			JOIN T_AUTORIZIMTRUPI ON T_AUTORIZIMTRUPI.IDAUTORIZIMKOKA=T_AUTORIZIMKOKA.IDAUTORIZIMEKOKA
			INNER JOIN T_NDERMARJE ON T_AUTORIZIMKOKA.IDNDERMARJE = T_NDERMARJE.IDNDERMARJE
			WHERE T_AUTORIZIMTRUPI.IDPERDORUESI not in (SELECT IDPERDORUES FROM T_PERDORUESI WHERE IDSTATUSDOK=1 AND PERDORUESUSERNAME=''' + @PERDORUES + ''') 
			AND  T_NDERMARJE.NDERMARJEKODI=''' + @NDERMARRJEKOD + '''
			AND T_LIDHJEAUTORIZIM.IDSTATUSDOK=1 AND IDLLOJI in (select idllojbuxheti from T_LLOJBUXHETI  where KODLLOJBUXHETI=''KlientFurnitor''))))  '
		end
ELSE 
begin
	SET @AUTORIZIM = ''
	SET @JOAUTORIZIM =''
end


SET @SHPREHJE = ' WITH TRUPIJASHTE AS (
SELECT	KODKLIENTFURNITOR, EMERKERKRIMIKF, EMERTIMIKF, NIPTKF, MONEDHAKOD, PERSHKRIMNIVELCMIMI, ZBRITJEANALITIKE, TELKF, EMAILKF,SHTETIKF,AUTONGARKESE, TIPIID, FAXKF, ADRESA, QYTETIKODI, KODKATEGORIZBRITJE, 
AKTIVKF, PERSHKRIMGRUPI1, PERSHKRIMGRUPI2, PERSHKRIMGRUPI3, KODNIVELZBRITJE, Agjentipare, Supervizori, DTMODIFIKIM, IDSTATUSDOK, LIMITBLLOKUES, LIMITPARALAJMERUES, CELKF, KOORDINATA, Sinkronizuar, CASE PROSPEKT WHEN 0 THEN ''false'' ELSE ''true'' END as PROSPEKT, KODIMOBILE, KODGRUP1, KODGRUP2,   ID, KODKFKRYESOR, BRUTONETONIVELCMIMI,
METODA ,TVSHKODI , NRTVSH , LICENCA , rk_kukureci , ROW_NUMBER() OVER(PARTITION BY TRUPIBRENDA.KODKLIENTFURNITOR  ORDER BY DTMODIFIKIM DESC) rk 
FROM
(
	SELECT   KODKLIENTFURNITOR, EMERKERKRIMIKF, EMERTIMIKF, NIPTKF, MONEDHAKOD, PERSHKRIMNIVELCMIMI, ZBRITJEANALITIKE, TELKF, EMAILKF,SHTETIKF,AUTONGARKESE, TIPIID, FAXKF, ADRESA, QYTETIKODI, KODKATEGORIZBRITJE, 
AKTIVKF, PERSHKRIMGRUPI1, PERSHKRIMGRUPI2, PERSHKRIMGRUPI3, KODNIVELZBRITJE, Agjentipare, Supervizori, DTMODIFIKIM, IDSTATUSDOK, LIMITBLLOKUES, LIMITPARALAJMERUES, CELKF, KOORDINATA, Sinkronizuar , PROSPEKT,  KODIMOBILE, KODGRUP1, KODGRUP2,   ID, KODKFKRYESOR, BRUTONETONIVELCMIMI, METODA, TVSHKODI , NRTVSH ,LICENCA
,ROW_NUMBER() OVER(PARTITION BY KUKURECI.KODKLIENTFURNITOR, DTMODIFIKIM ORDER BY IDSTATUSDOK ) rk_kukureci 
	FROM (

	SELECT T_KLIENTFURNITOR.IDKLIENTFURNITOR as ID, T_KLIENTFURNITOR.KODKLIENTFURNITOR, T_KLIENTFURNITOR.EMERKERKRIMIKF, T_KLIENTFURNITOR.EMERTIMIKF, T_KLIENTFURNITOR.NIPTKF, T_MONEDHA.MONEDHAKOD, T_NIVELCMIMI.KODNIVELCMIMI AS PERSHKRIMNIVELCMIMI, T_KLIENTFURNITOR.ZBRITJEANALITIKE, T_KLIENTFURNITOR.TELKF,
	T_KLIENTFURNITOR.EMAILKF,T_KLIENTFURNITOR.SHTETIKF,T_KLIENTFURNITOR.AUTONGARKESE, T_KLIENTFURNITOR.TIPIID, T_KLIENTFURNITOR.FAXKF, ADRESA, QYTETIKODI, KODKATEGORIZBRITJE, T_KLIENTFURNITOR.AKTIVKF, 
	LEFT(GRUPEKF1.PERSHKRIMGRUPI,50) AS PERSHKRIMGRUPI1, LEFT(GRUPEKF2.PERSHKRIMGRUPI,50) AS PERSHKRIMGRUPI2, LEFT(GRUPEKF3.PERSHKRIMGRUPI,50) AS PERSHKRIMGRUPI3, T_NIVELZBRITJE.KODNIVELZBRITJE, 
	 ISNULL(CASE WHEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'') 
	   > ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') 
	   THEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'')
		 ELSE ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') END, ''1/1/1920'') AS DTMODIFIKIM,
	AGJ1.KODIAGJENTSHITJE AS Agjentipare, AGJ2.KODIAGJENTSHITJE AS Supervizori, T_KLIENTFURNITOR.IDSTATUSDOK, T_KLIENTFURNITOR.LIMITBLLOKUES, T_KLIENTFURNITOR.LIMITPARALAJMERUES, T_KLIENTFURNITOR.CELKF, 
	T_KLIENTFURNITOR.KOORDINATA.STAsText() AS KOORDINATA, ''true'' as Sinkronizuar,  T_KLIENTFURNITOR.PROSPEKT, T_KLIENTFURNITOR.KODIMOBILE, GRUPEKF1.KODGRUPI as KODGRUP1, GRUPEKF2.KODGRUPI AS KODGRUP2, KFKRYESOR.IDKLIENTFURNITOR AS IDKFKRYESOR, KFKRYESOR.KODKLIENTFURNITOR AS KODKFKRYESOR, T_NIVELCMIMI.BRUTONETONIVELCMIMI, 
	CASE WHEN T_KLIENTFURNITOR.IDMETODA = 0 THEN ''Mirebesim'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 4 THEN ''Kesh'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 5 THEN ''Kesh'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 6 THEN ''Kesh'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 7 THEN ''Kesh'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 8 THEN ''Arke'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 9 THEN ''Karte Krediti'' 
		 WHEN T_KLIENTFURNITOR.IDMETODA = 10 THEN ''Kesh'' ELSE '''' END AS METODA ,T_TAKSAT.KODI AS TVSHKODI , T_KLIENTFURNITOR.NRTVSH ,T_KLIENTFURNITOR.LICENCA
	FROM T_KLIENTFURNITOR
	  INNER JOIN T_NDERMARJE ON T_NDERMARJE.IDNDERMARJE =  T_KLIENTFURNITOR.IDNDERMARJE
	  LEFT OUTER JOIN T_LLOGARI ON T_LLOGARI.IDLLOGARI = T_KLIENTFURNITOR.IDLLOGARI
	  LEFT OUTER JOIN T_MONEDHA ON T_MONEDHA.IDMONEDHA = T_LLOGARI.MONEDHA
	  LEFT OUTER JOIN T_NIVELCMIMI ON T_NIVELCMIMI.IDNIVELCMIMI = T_KLIENTFURNITOR.IDNIVELCMIMI
	  LEFT OUTER JOIN T_ADRESAKLIENTFURNITOR ON T_ADRESAKLIENTFURNITOR.IDKLIENTFURNITOR = T_KLIENTFURNITOR.IDKLIENTFURNITOR
	  LEFT OUTER JOIN T_QYTETI ON T_QYTETI.IDQYTETI = T_KLIENTFURNITOR.QYTETIKF '
SET @SHPREHJE1 = '  LEFT OUTER JOIN T_KOKAKATEGORIZBRITJE ON T_KOKAKATEGORIZBRITJE.IDKOKAKATEGORIZBRITJE = T_KLIENTFURNITOR.IDKATZBRITJE
	  LEFT OUTER JOIN T_GRUPEKF AS GRUPEKF1 ON GRUPEKF1.IDGRUPI = T_KLIENTFURNITOR.GRUPIM1KF
	  LEFT OUTER JOIN T_GRUPEKF AS GRUPEKF2 ON GRUPEKF2.IDGRUPI = T_KLIENTFURNITOR.GRUPIM2KF
	  LEFT OUTER JOIN T_GRUPEKF AS GRUPEKF3 ON GRUPEKF3.IDGRUPI = T_KLIENTFURNITOR.GRUPIM3KF
	  LEFT OUTER JOIN T_NIVELZBRITJE ON T_KLIENTFURNITOR.ZBRITJEANALITIKE = T_NIVELZBRITJE.IDNIVELZBRITJE
	  LEFT OUTER JOIN T_AGJENTSHITJE AGJ1 ON T_KLIENTFURNITOR.IDPERFAQESUESSHITJE=AGJ1.IDAGJENTSHITJE
	  LEFT OUTER JOIN T_AGJENTSHITJE AGJ2 ON T_KLIENTFURNITOR.IDPERFAQESUESSHITJE=AGJ2.IDAGJENTSHITJE
	  LEFT OUTER JOIN T_KLIENTFURNITOR KFKRYESOR ON T_KLIENTFURNITOR.IDKLIENTFURNITORKRYESOR= KFKRYESOR.IDKLIENTFURNITOR
	  LEFT OUTER JOIN T_TAKSAT ON T_TAKSAT.IDTAKSA = T_KLIENTFURNITOR.IDTVSH
	  LEFT OUTER JOIN  T_LIDHJEAUTORIZIM ON T_LIDHJEAUTORIZIM.IDLIDHESE=T_KLIENTFURNITOR.IDKLIENTFURNITOR
	  LEFT OUTER JOIN T_AUTORIZIMKOKA ON T_AUTORIZIMKOKA.IDAUTORIZIMEKOKA=T_LIDHJEAUTORIZIM.IDAUTORIZIMEKOKA

	WHERE  ISNULL(CASE WHEN ISNULL(CASE WHEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'') 
	   > ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') 
	   THEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'')
		 ELSE ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') END, ''1/1/1920'') >ISNULL(CASE WHEN T_AUTORIZIMKOKA.DTMODIFIKIMI IS NULL THEN T_AUTORIZIMKOKA.DTKRIJIMI ELSE T_AUTORIZIMKOKA.DTMODIFIKIMI END, ''01/01/1920'')
		  THEN ISNULL(CASE WHEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'') 
	   > ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') 
	   THEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'')
		 ELSE ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') END, ''1/1/1920'') ELSE ISNULL(CASE WHEN T_AUTORIZIMKOKA.DTMODIFIKIMI IS NULL THEN T_AUTORIZIMKOKA.DTKRIJIMI ELSE T_AUTORIZIMKOKA.DTMODIFIKIMI END, ''01/01/1920'') END,''1/1/1900'') > ''' + @DTFUNDITLEXUAR + '''
	  AND NDERMARJEKODI = ''' + @NDERMARRJEKOD + ''' AND T_NDERMARJE.IDSTATUSDOK = 1 AND  T_KLIENTFURNITOR.LLOJIKF = 1 '+@AUTORIZIM+' 
  '
    IF (CONVERT(datetime, @DTFUNDITLEXUAR) = @DATEMINIMALE)
	SET @SHPREHJE1 += ' AND T_KLIENTFURNITOR.IDSTATUSDOK=1 '

   IF(@PERDORUES <> '' AND CONVERT(datetime, @DTFUNDITLEXUAR) > @DATEMINIMALE)
	  SET @SHPREHJE2 = ' 
  UNION
		SELECT T_KLIENTFURNITOR.IDKLIENTFURNITOR, T_KLIENTFURNITOR.KODKLIENTFURNITOR, T_KLIENTFURNITOR.EMERKERKRIMIKF, T_KLIENTFURNITOR.EMERTIMIKF, T_KLIENTFURNITOR.NIPTKF, '''' MONEDHAKOD, 
		'''' PERSHKRIMNIVELCMIMI, T_KLIENTFURNITOR.ZBRITJEANALITIKE, T_KLIENTFURNITOR.TELKF,T_KLIENTFURNITOR.EMAILKF,T_KLIENTFURNITOR.SHTETIKF,T_KLIENTFURNITOR.AUTONGARKESE, T_KLIENTFURNITOR.TIPIID, T_KLIENTFURNITOR.FAXKF,'''' ADRESA,'''' QYTETIKODI,'''' KODKATEGORIZBRITJE, T_KLIENTFURNITOR.AKTIVKF, 
	'''' PERSHKRIMGRUPI1,'''' AS PERSHKRIMGRUPI2, '''' AS PERSHKRIMGRUPI3, '''' KODNIVELZBRITJE, ISNULL(CASE WHEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'') 
	   > ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') 
	   THEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'')
		 ELSE ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') END, ''1/1/1920'') AS DTMODIFIKIM,
	'''' Agjentipare, '''' Supervizori, 2 IDSTATUSDOK, T_KLIENTFURNITOR.LIMITBLLOKUES, T_KLIENTFURNITOR.LIMITPARALAJMERUES,
	 T_KLIENTFURNITOR.CELKF, 
		T_KLIENTFURNITOR.KOORDINATA.STAsText() AS KOORDINATA, ''true'' as Sinkronizuar,  T_KLIENTFURNITOR.PROSPEKT, T_KLIENTFURNITOR.KODIMOBILE, '''' KODGRUP1,
	'''' KODGRUP2, 0 IDKFKRYESOR, '''' KODKFKRYESOR, 0 BRUTONETONIVELCMIMI,
	 '''' METODA ,T_TAKSAT.KODI AS TVSHKODI  ,T_KLIENTFURNITOR.NRTVSH ,T_KLIENTFURNITOR.LICENCA 
	 FROM T_KLIENTFURNITOR
	  INNER JOIN T_NDERMARJE ON T_NDERMARJE.IDNDERMARJE =  T_KLIENTFURNITOR.IDNDERMARJE
	  LEFT OUTER JOIN T_NIVELCMIMI ON T_NIVELCMIMI.IDNIVELCMIMI = T_KLIENTFURNITOR.IDNIVELCMIMI
	  LEFT OUTER JOIN T_TAKSAT ON T_TAKSAT.IDTAKSA = T_KLIENTFURNITOR.IDTVSH
	  LEFT OUTER JOIN  T_LIDHJEAUTORIZIM ON T_LIDHJEAUTORIZIM.IDLIDHESE=T_KLIENTFURNITOR.IDKLIENTFURNITOR
	  LEFT OUTER JOIN T_AUTORIZIMKOKA ON T_AUTORIZIMKOKA.IDAUTORIZIMEKOKA=T_LIDHJEAUTORIZIM.IDAUTORIZIMEKOKA

	  WHERE  T_NDERMARJE.IDSTATUSDOK = 1 AND 
	  ISNULL(CASE WHEN ISNULL(CASE WHEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'') 
	   > ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') 
	   THEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'')
		 ELSE ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') END, ''1/1/1920'') >ISNULL(CASE WHEN T_AUTORIZIMKOKA.DTMODIFIKIMI IS NULL THEN T_AUTORIZIMKOKA.DTKRIJIMI ELSE T_AUTORIZIMKOKA.DTMODIFIKIMI END, ''01/01/1920'')
		  THEN ISNULL(CASE WHEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'') 
	   > ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') 
	   THEN ISNULL(CASE WHEN T_NIVELCMIMI.DTMODIFIKIMI IS NULL THEN T_NIVELCMIMI.DTKRIJIMI ELSE T_NIVELCMIMI.DTMODIFIKIMI END, ''01/01/1920'')
		 ELSE ISNULL(CASE WHEN T_KLIENTFURNITOR.DTMODIFIKIMI IS NULL THEN T_KLIENTFURNITOR.DTKRIJIMI ELSE T_KLIENTFURNITOR.DTMODIFIKIMI END, ''01/01/1920'') END, ''1/1/1920'') ELSE ISNULL(CASE WHEN T_AUTORIZIMKOKA.DTMODIFIKIMI IS NULL THEN T_AUTORIZIMKOKA.DTKRIJIMI ELSE T_AUTORIZIMKOKA.DTMODIFIKIMI END, ''01/01/1920'') END,''1/1/1900'') > ''' + @DTFUNDITLEXUAR + '''
	  AND NDERMARJEKODI = ''' + @NDERMARRJEKOD + ''' 
	   AND T_KLIENTFURNITOR.LLOJIKF = 1 '+ @JOAUTORIZIM +'  
	   	 )KUKURECI
	 ) TRUPIBRENDA 
	) ' 

  ELSE
	  SET @SHPREHJE2='
)KUKURECI
 ) TRUPIBRENDA 
	) '

	SET @SHPREHJE3 = 'SELECT KODKLIENTFURNITOR, EMERKERKRIMIKF, EMERTIMIKF, NIPTKF, MONEDHAKOD, PERSHKRIMNIVELCMIMI, ZBRITJEANALITIKE, TELKF, EMAILKF,SHTETIKF,AUTONGARKESE, TIPIID, FAXKF, ADRESA, QYTETIKODI, KODKATEGORIZBRITJE, 
AKTIVKF, PERSHKRIMGRUPI1, PERSHKRIMGRUPI2, PERSHKRIMGRUPI3, KODNIVELZBRITJE, Agjentipare, Supervizori, DTMODIFIKIM, IDSTATUSDOK, LIMITBLLOKUES, LIMITPARALAJMERUES, CELKF, KOORDINATA, Sinkronizuar,PROSPEKT, KODIMOBILE, KODGRUP1, KODGRUP2,   ID, KODKFKRYESOR, BRUTONETONIVELCMIMI,   METODA , TVSHKODI ,NRTVSH ,LICENCA
FROM (SELECT KODKLIENTFURNITOR, EMERKERKRIMIKF, EMERTIMIKF, NIPTKF, MONEDHAKOD, PERSHKRIMNIVELCMIMI, ZBRITJEANALITIKE, TELKF, EMAILKF,SHTETIKF,AUTONGARKESE, TIPIID, FAXKF, ADRESA, QYTETIKODI, KODKATEGORIZBRITJE, 
AKTIVKF, PERSHKRIMGRUPI1, PERSHKRIMGRUPI2, PERSHKRIMGRUPI3, KODNIVELZBRITJE, Agjentipare, Supervizori, DTMODIFIKIM, IDSTATUSDOK, LIMITBLLOKUES, LIMITPARALAJMERUES, CELKF, KOORDINATA, Sinkronizuar, PROSPEKT, KODIMOBILE, KODGRUP1, KODGRUP2,  ID, KODKFKRYESOR, BRUTONETONIVELCMIMI, ROW_NUMBER() OVER (ORDER BY DTMODIFIKIM, ID) AS NR_RRESHTI, METODA ,TVSHKODI ,NRTVSH ,LICENCA
FROM (
 '
 --selektojme vetem rreshtin e pare per cdo grupim
SET @SHPREHJE4='
				Select  KODKLIENTFURNITOR, EMERKERKRIMIKF, EMERTIMIKF, NIPTKF, MONEDHAKOD, PERSHKRIMNIVELCMIMI, ZBRITJEANALITIKE, TELKF, EMAILKF,SHTETIKF,AUTONGARKESE, TIPIID, FAXKF, ADRESA, QYTETIKODI, KODKATEGORIZBRITJE, 
						AKTIVKF, PERSHKRIMGRUPI1, PERSHKRIMGRUPI2, PERSHKRIMGRUPI3, KODNIVELZBRITJE, Agjentipare, Supervizori, DTMODIFIKIM, IDSTATUSDOK, LIMITBLLOKUES, LIMITPARALAJMERUES, CELKF, 
						KOORDINATA, Sinkronizuar, PROSPEKT, KODIMOBILE, KODGRUP1, KODGRUP2,   ID, KODKFKRYESOR, BRUTONETONIVELCMIMI,  METODA ,TVSHKODI ,NRTVSH ,LICENCA
  FROM
					TRUPIJASHTE t
					WHERE t.rk=1 AND t.rk_kukureci=1' 
SET @SHPREHJE5 =' ) AS TRUPI ) AS CHUNK '

SET @SHPREHJE6 = ' WHERE  NR_RRESHTI BETWEEN (' + @NRSEL + ' * ' + @NRCHUNK + ' - ' + @NRSEL + ' + 1) AND (' + @NRSEL + ' * ' + @NRCHUNK + ') '	
SET @SHPREHJE7 = ' ORDER BY DTMODIFIKIM ' 

IF (@NRSEL > 0 AND  @NRCHUNK > 0)
BEGIN
  EXEC  (@SHPREHJE+ @SHPREHJE1 + @SHPREHJE2  + @SHPREHJE3 + @SHPREHJE4+ @SHPREHJE5 + @SHPREHJE6 + @SHPREHJE7)
  PRINT (@SHPREHJE+@SHPREHJE1 + @SHPREHJE2  + @SHPREHJE3 + @SHPREHJE4+ @SHPREHJE5 + @SHPREHJE6 + @SHPREHJE7)
END
ELSE
BEGIN 
  EXEC  (@SHPREHJE+@SHPREHJE1 + @SHPREHJE2 +  @SHPREHJE3+  @SHPREHJE4 +  @SHPREHJE5  + @SHPREHJE7)
  PRINT (@SHPREHJE)
  PRINT (@SHPREHJE1)
  PRINT (@SHPREHJE2)
  PRINT (@SHPREHJE3)
  PRINT (@SHPREHJE4)
  PRINT (@SHPREHJE5)
  PRINT (@SHPREHJE7)
END 
END