<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Ds_KartelaAnalitikeDokumentaInventarizimi" targetNamespace="http://tempuri.org/Ds_KartelaAnalitikeDokumentaInventarizimi.xsd" xmlns:mstns="http://tempuri.org/Ds_KartelaAnalitikeDokumentaInventarizimi.xsd" xmlns="http://tempuri.org/Ds_KartelaAnalitikeDokumentaInventarizimi.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:msprop="urn:schemas-microsoft-com:xml-msprop" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:annotation>
    <xs:appinfo source="urn:schemas-microsoft-com:xml-msdatasource">
      <DataSource DefaultConnectionIndex="4" FunctionsComponentName="QueriesTableAdapter" Modifier="AutoLayout, AnsiClass, Class, Public" SchemaSerializationMode="IncludeSchema" xmlns="urn:schemas-microsoft-com:xml-msdatasource">
        <Connections>
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="webinfpreprodConnectionString" IsAppSettingsProperty="true" Modifier="Assembly" Name="webinfpreprodConnectionString (Settings)" ParameterPrefix="@" PropertyReference="ApplicationSettings.AlphaWebReports.Magazina.Properties.Settings.GlobalReference.Default.proveConnectionString" Provider="System.Data.SqlClient" />
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="webinfpreprodConnectionString1" IsAppSettingsProperty="true" Modifier="Assembly" Name="webinfpreprodConnectionString1 (Settings)" ParameterPrefix="@" PropertyReference="ApplicationSettings.AlphaWebReports.Magazina.Properties.Settings.GlobalReference.Default.webinfpreprodConnectionString1" Provider="System.Data.SqlClient" />
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="connStringAlpha" IsAppSettingsProperty="true" Modifier="Assembly" Name="connStringAlpha (Settings)" ParameterPrefix="@" PropertyReference="ApplicationSettings.AlphaWebReports.Magazina.Properties.Settings.GlobalReference.Default.connStringAlpha" Provider="System.Data.SqlClient" />
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="webinfConnectionString" IsAppSettingsProperty="true" Modifier="Assembly" Name="webinfConnectionString (Settings)" ParameterPrefix="@" PropertyReference="ApplicationSettings.AlphaWebReports.Magazina.Properties.Settings.GlobalReference.Default.webinfConnectionString" Provider="System.Data.SqlClient" />
          <Connection AppSettingsObjectName="Settings" AppSettingsPropertyName="preprodConnectionString" IsAppSettingsProperty="true" Modifier="Assembly" Name="preprodConnectionString (Settings)" ParameterPrefix="@" PropertyReference="ApplicationSettings.AlphaWebReports.Magazina.Properties.Settings.GlobalReference.Default.preprodConnectionString" Provider="System.Data.SqlClient" />
        </Connections>
        <Tables>
          <TableAdapter BaseClass="System.ComponentModel.Component" DataAccessorModifier="AutoLayout, AnsiClass, Class, Public" DataAccessorName="PRC_RAP_KartelaAnalitikeDokumentaInventarizimiTableAdapter" 