//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DbCore.KasaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KasaWebServiceSoap", Namespace="http://vodafone.al/")]
    public partial class KasaWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PrintoKuponTatimorOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintoKuponJoTatimorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KasaWebService() {
            this.Url = global::DbCore.Properties.Settings.Default.DbCore_KasaService_KasaWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PrintoKuponTatimorCompletedEventHandler PrintoKuponTatimorCompleted;
        
        /// <remarks/>
        public event PrintoKuponJoTatimorCompletedEventHandler PrintoKuponJoTatimorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vodafone.al/PrintoKuponTatimor", RequestNamespace="http://vodafone.al/", ResponseNamespace="http://vodafone.al/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PrintoKuponTatimor(CommandRequest commReq) {
            object[] results = this.Invoke("PrintoKuponTatimor", new object[] {
                        commReq});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PrintoKuponTatimorAsync(CommandRequest commReq) {
            this.PrintoKuponTatimorAsync(commReq, null);
        }
        
        /// <remarks/>
        public void PrintoKuponTatimorAsync(CommandRequest commReq, object userState) {
            if ((this.PrintoKuponTatimorOperationCompleted == null)) {
                this.PrintoKuponTatimorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintoKuponTatimorOperationCompleted);
            }
            this.InvokeAsync("PrintoKuponTatimor", new object[] {
                        commReq}, this.PrintoKuponTatimorOperationCompleted, userState);
        }
        
        private void OnPrintoKuponTatimorOperationCompleted(object arg) {
            if ((this.PrintoKuponTatimorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintoKuponTatimorCompleted(this, new PrintoKuponTatimorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vodafone.al/PrintoKuponJoTatimor", RequestNamespace="http://vodafone.al/", ResponseNamespace="http://vodafone.al/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PrintoKuponJoTatimor(CommandRequest commReq) {
            object[] results = this.Invoke("PrintoKuponJoTatimor", new object[] {
                        commReq});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PrintoKuponJoTatimorAsync(CommandRequest commReq) {
            this.PrintoKuponJoTatimorAsync(commReq, null);
        }
        
        /// <remarks/>
        public void PrintoKuponJoTatimorAsync(CommandRequest commReq, object userState) {
            if ((this.PrintoKuponJoTatimorOperationCompleted == null)) {
                this.PrintoKuponJoTatimorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintoKuponJoTatimorOperationCompleted);
            }
            this.InvokeAsync("PrintoKuponJoTatimor", new object[] {
                        commReq}, this.PrintoKuponJoTatimorOperationCompleted, userState);
        }
        
        private void OnPrintoKuponJoTatimorOperationCompleted(object arg) {
            if ((this.PrintoKuponJoTatimorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintoKuponJoTatimorCompleted(this, new PrintoKuponJoTatimorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vodafone.al/")]
    public partial class CommandRequest {
        
        private string requestSystemField;
        
        private string transactionIDField;
        
        private string ipField;
        
        private System.Nullable<int> idShopField;
        
        private string advertisementField;
        
        private Item[] itemsField;
        
        /// <remarks/>
        public string RequestSystem {
            get {
                return this.requestSystemField;
            }
            set {
                this.requestSystemField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdShop {
            get {
                return this.idShopField;
            }
            set {
                this.idShopField = value;
            }
        }
        
        /// <remarks/>
        public string Advertisement {
            get {
                return this.advertisementField;
            }
            set {
                this.advertisementField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vodafone.al/")]
    public partial class Item {
        
        private int departamentiField;
        
        private string emertimiField;
        
        private float sasiaField;
        
        private float cmimiField;
        
        /// <remarks/>
        public int Departamenti {
            get {
                return this.departamentiField;
            }
            set {
                this.departamentiField = value;
            }
        }
        
        /// <remarks/>
        public string Emertimi {
            get {
                return this.emertimiField;
            }
            set {
                this.emertimiField = value;
            }
        }
        
        /// <remarks/>
        public float Sasia {
            get {
                return this.sasiaField;
            }
            set {
                this.sasiaField = value;
            }
        }
        
        /// <remarks/>
        public float Cmimi {
            get {
                return this.cmimiField;
            }
            set {
                this.cmimiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PrintoKuponTatimorCompletedEventHandler(object sender, PrintoKuponTatimorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintoKuponTatimorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintoKuponTatimorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PrintoKuponJoTatimorCompletedEventHandler(object sender, PrintoKuponJoTatimorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintoKuponJoTatimorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintoKuponJoTatimorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591